### ISSUE TITLE
Possibly add speaker note about special treatment of arrays in Arrays and for loops section.

### ISSUE THREAD

**Issue by dyoo** [google/comprehensive-rust#1063]
In the section on `for` loops: https://google.github.io/comprehensive-rust/exercises/day-1/for-loops.html, the main function iterates over an array.

But there's a subtle issue here: the first loop is doing an implicit copy!  Because we're accessing the array after the initial loop, and because into_iter() is consuming the array, an implicit array copy is happening here to make everything work.

```
    let array = [10, 20, 30];
    print!("Iterating over array:");
    for n in array {
       ...
    }
    ...
```

This snippet is hiding certain aspects of Rust that end up being things that Rust programmers have to deal with in practice (iter() versus into_iter(), ownership, etc.).  This feels like an opportunity to point this out, either in speaker notes or by improving the example.

Perhaps adjusting the example so it iterates over a reference to the array might be helpful?

```
    let array = [10, 20, 30];
    print!("Iterating over array:");
    for n in &array {
       ...
    }
    ...
```

The idea being that, by adding the reference operator there, it helps motivate certain questions and is a preview of the ownership issues that are covered later in the course.

**Comment by mgeisler** [comment]
Hi @dyoo! Those are good points, thanks!

I like the idea of iterating over a reference. Could you open a PR which makes this change? Feel free to also explain this in the speaker notes: the notes are super valuable for people who read the course without a Rust expert nearby.

**Comment by dyoo** [comment]
Acknowledged; sending https://github.com/google/comprehensive-rust/pull/1081.  Hope this helps!
