### ISSUE TITLE
Split solution pages into one page per problem

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1065]
When reviewing #913, I realized that we should show the solutions with one page per problem. Today, we show all solutions for Day N  on a single page and that's confusing (and less flexible if we move things around).

**Comment by dyoo** [comment]
I would like to work on this.

**Comment by dyoo** [comment]
Ah, okay.  Acknowledged.  Holding off then.  Let me withdraw https://github.com/google/comprehensive-rust/pull/1137 for now then.

**Comment by mgeisler** [comment]
> In fact, it would be interesting to think about how best to arrange the solutions. Perhaps we should just include each as a sub-slide of the exercise slide?

Yeah, the current "system" is just what came to mind first so we can certainly iterate on it :smile:

By sub-slide, do you mean as a note at the bottom of the page? I feel that makes it a bit too easy to go straight to the solution.

**Comment by djmitche** [comment]
No, I meant that the next slide would include the solution, but be nested below the exercise so that it doesn't get its own row in the table of contents.

```
  - [Exercise: ..](unsafe/exercise.md)
    - [Solution](unsafe/exercise/solution.md)
```

**Comment by mgeisler** [comment]
> No, I meant that the next slide would include the solution

Great, that could certainly work!
