### ISSUE TITLE
fr: problem translation

### ISSUE THREAD

**Issue by projectsbaptiste** [google/comprehensive-rust#1074]
problem translating into french .

in po/fr.po    ligne 2657

"Assurez-vous de demander à la classe dans quelles langues ils ont de l’expérience"
"Assurez-vous de demander à la classe dans quels langages ils ont de l’expérience"

 (langues mean French or English for Programming language we use langages) 
ref https://fr.wikipedia.org/wiki/Langage_de_programmation

thx for the rust tutorial.

(I tried to fix it but I couldn't find the procedure to do it. sorry if I do misstake in this post )

**Comment by mgeisler** [comment]
Hi @projectsbaptiste, thanks for the bug report! To fix this, we would need to update the [`po/fr.po` file](https://github.com/google/comprehensive-rust/edit/main/po/fr.po).

You could submit a pull request, or perhaps one of @sakex, @AdrienBaudemont, @yohcop, @KookaS, ... could do it.

**Comment by mgeisler** [comment]
@lb034582341, would you be able to fix this?

**Comment by AdrienBaudemont** [comment]
> Hi @projectsbaptiste, thanks for the bug report! To fix this, we would need to update the [`po/fr.po` file](https://github.com/google/comprehensive-rust/edit/main/po/fr.po).
> 
> You could submit a pull request, or perhaps one of @sakex, @AdrienBaudemont, @yohcop, @KookaS, ... could do it.

Hello!
I have opened a PR to fix this issue. Thanks for reporting it!
