### ISSUE TITLE
zh-TW: "類似" is slightly werid since "編譯器擴充" isn't really a thing.

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1080]
> nit: "類似" is slightly werid since "編譯器擴充" isn't really a thing.  But I'm not sure what'd be a better expression... 可想像成編譯器的擴充? :-/

_Originally posted by @victorhsieh in https://github.com/google/comprehensive-rust/pull/824#discussion_r1270810505_

**Comment by henrif75** [comment]
Closing this issue since the v2 translation was published after.
