### ISSUE TITLE
Create more and better exercises

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1082]
One of the more consistent asks from course participants is more exercises. People like the interactive form, but they also want to play with Rust themselves.

The current exercises have some problems:

- They sometimes rely on content not fully covered at the time (Day 1 afternoon exercises uses methods which are not fully introduced at this point)
- They sometimes ask you to solve a problem where the problem itself is challenging (the multi-threaded link checker in the Concurrency section is more of a mini-project than an exercise).

To solve the above, we should write new exercises. The exercises should be trivial: the participants should be able to come up with a correct solution in 30 seconds — the challenge should be "How to implement this in Rust?" The Luhn exercise is a good example: it's easy to see how to solve it in a C-like way where you just iterate through the characters one by one and ignore most error cases. So students can start with that version and iterate on it to make it nicer.

Exercises can also be less free-form than the current exercises. If we provide more scaffolding for the students, we can guide them better and ask them to implement a bigger task. This is something we should do for the link checker exercise. We should provide most of the solution and just let students fill in 20-30 missing lines. That reflects how engineers typically work: you read a lot more code than you write and you are often asked to work in an existing system.

**Comment by djmitche** [comment]
The reorg being planned in #1073 involves a lot more "spots" for exercises, so it'd be great to write exercises that fit in those spots, rather than just more exercises :)

There are already a few new exercises mentioned in that PR (but not fully written yet), but a bunch of segments just have "Exercise: ???" at the end.

**Comment by djmitche** [comment]
Yes - we definitely need to have better, shorter time-boxes for the exercises. I think it's OK for some segments to have slightly longer or shorter exercises, but probably 15 minutes is the max.

**Comment by mgeisler** [comment]
The rewrite in #1073 has a lot more exercises, so we can mark this as fixed when that is merged.
