### ISSUE TITLE
Use `typos`

### ISSUE THREAD

**Issue by mo8it** [google/comprehensive-rust#1093]
[`typos`](https://github.com/crate-ci/typos) currently reports two typos. Maybe add it to the CI?

**Comment by mgeisler** [comment]
Hi @mo8it, that looks like a useful tool! I would be happy take a PR for this.

**Comment by antoniolinhart** [comment]
Hey all,

I'd like to try adding this to the CI! I haven't used GH actions before so I'm interested in learning about how it works. May I take this as a first issue?

Antonio

**Comment by mgeisler** [comment]
Thanks @antoniolinhart! You'll need to modify the files under `.github/workflows/`. When you open a PR, then you'll be able to see the results of your modifications in the "Checks" tab.
