### ISSUE TITLE
Create GitHub workflow for refreshing individual files

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1205]
It should be possible to create a GitHub workflow which runs

```shell
MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot"}}' mdbook build -d po
msgmerge --update po/XX.po po/messages.pot
```

for a language. I believe it's also possible to trigger workflows directly in the [Actions tab](https://github.com/google/comprehensive-rust/actions). The workflow could then do the `msgmerge`, open a PR and perhaps even close the PR automatically.

**Comment by dtee1** [comment]
Could this be assigned to me?

**Comment by mgeisler** [comment]
Hi @dtee1, sure! Please let us know if you run into any problems with this!

**Comment by mgeisler** [comment]
I don't think this is super important, and with the idea of using a translation platform (#1305), we won't need this going forward.
