### ISSUE TITLE
Move CSS files into `theme/` folder

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1226]
The top-level folder has become crowded and I would like to move the many CSS files into the `theme/` folder (or some other nested place).

If other support files can be moved as well, all the better.

**Comment by hmn53** [comment]
Hey @mgeisler, I can give it a try. Can you assign this to me?

**Comment by mgeisler** [comment]
Hey @hmn53, sure, it's all yours!

My only concern here is that `mdbook build` should still copy the files over to the `book/` directory so that nothing breaks.

**Comment by hmn53** [comment]
Got it @mgeisler. Thanks a lot!
