### ISSUE TITLE
Fix resolver setting

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1249]
Our CI runs are outputting the following every time `mdbook-course` and `mdbook-exerciser` are installed:

```
cargo install --path mdbook-exerciser --locked
  
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```

We should probably follow the advice given here to silence the warnings.

**Comment by friendlymatthew** [comment]
Hi may I take on this issue?

**Comment by mgeisler** [comment]
Hi @friendlymatthew (such a cool username!), of course, it's all yours!

**Comment by friendlymatthew** [comment]
@mgeisler  Thanks :)

I specified the resolver within the base `Cargo.toml` file. I just signed the CLA so hopefully it gets approved quick!

In the mean time, I'll look for other work :)

**Comment by mgeisler** [comment]
Awesome, thanks again @friendlymatthew! Perhaps you would be for fixing some annoyences in the mdbook-exerciser tool we use? See #625 for that. Otherwise just look around at the many open issues here and in [mdbook-i18n-helpers](https://github.com/google/mdbook-i18n-helpers) :smile:
