### ISSUE TITLE
Could we avoid abbr for translation purpose?

### ISSUE THREAD

**Issue by HidenoriKobayashi** [google/comprehensive-rust#1284]
The \<abbr\> tags seem not work well for our translations. These are the two problems that I face now while translating [src/bare-metal/microcontrollers/probe-rs.md](https://raw.githubusercontent.com/google/comprehensive-rust/main/src/bare-metal/microcontrollers/probe-rs.md).

- One sentence is chopped into small chunks. This makes it difficult to translate into a language that has different ordering constraints and does not use space characters as in English. (For example, it would be much easier if this is part of a whole sentence: https://github.com/google/comprehensive-rust/blob/4e768e2e369cd71eb2a34fcfd3a6ead77cafba26/po/ja.po#L13377)
- It seems the paragraph separation/structure got confused. For example, the paragaph starting with "\`cargo-embed\` is a cargo ..." cannot be separated from the bullet list above it. What I see is the first word (`cargo-embed\`) being appended to the last item (Cargo integration).

I confirmed that removing those tags and appending the non-abbreviation in parentheses solves the above. An example would be:
```
-* <abbr title="Serial Wire Debug">SWD</abbr> and JTAG via CMSIS-DAP, ST-Link and J-Link probes
-* GDB stub and Microsoft <abbr title="Debug Adapter Protocol">DAP</abbr> server
+* SWD (Serial Wire Debug) and JTAG via CMSIS-DAP, ST-Link and J-Link probes
+* GDB stub and Microsoft DAP (Debug Adapter Protocol) server
```

**Comment by mgeisler** [comment]
Hi @HidenoriKobayashi, I would suggest that we don't add the `<abbr>` tag as well: we're writing Markdown, not HTML :-)

Could you make a PR to remove all such tags?

> * It seems the paragraph separation/structure got confused. For example, the paragaph starting with "`cargo-embed` is a cargo ..." cannot be separated from the bullet list above it. What I see is the first word (`cargo-embed\`) being appended to the last item (Cargo integration).

This sounds like a bug in https://github.com/google/mdbook-i18n-helpers — can I get you to open an issue with it there? Then we'll see about fixing it as soon as possible.

**Comment by HidenoriKobayashi** [comment]
Hi @mgeisler,

Re: removing the tag, I'll create a PR sometime this week, hopefully.

Re: confusion of mdbook, I'll open an issue as suggested. I personally would not consider this specific case as bug if it does not intend to handle any HTML tags. However I'll still open an issue, since there might be a potential bug that could affect a supported case.

Thanks for the suggestions!

**Comment by mgeisler** [comment]
> I personally would not consider this specific case as bug if it does not intend to handle any HTML tags. However I'll still open an issue, since there might be a potential bug that could affect a supported case.

I think we should handle this case in mdbook-i18n-helpers.

**Comment by HidenoriKobayashi** [comment]
I'm closing this issue,because
- the issue in the title should have been resolved by the PR
- the potential issue in the i18n-helpers has another issue in its own project
