### ISSUE TITLE
26.3.2 Deriving Error enums

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1285]
### Discussed in https://github.com/google/comprehensive-rust/discussions/1281

<div type='discussions-op-text'>

<sup>Originally posted by **njr0** September 29, 2023</sup>
I think a little but more explanation would be helpful here.

I don't think the course has mentioned positional arguments to format strings before, and though I think people will guess that's what `"{0}"` is, it's not immedately apparent, looking at the code, that there's a argument for it to format.

Similarly, I think a few words about `#[error` and `#[from` might be useful.

</div>

**Comment by fw-immunant** [comment]
See #2027.
