### ISSUE TITLE
Evaluate translation platforms

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1305]
We have so far let translators come up with their own workflows. This has worked remarkably well, despite having to juggle huge PO files with around 20k lines.

There are alternatives to editing the PO files locally: there exists several different online translation platforms which offers a better interface plus automation. A quick search finds sites such as

- https://crowdin.com/
- https://transifex.com/
- https://lokalise.com/
- https://poeditor.com/

There are many others, so this is just a selection.

# Features

- Support for PO files:
  - It is important that they should not mangle the POT-Creation-Date header we rely on (#1243).
  - An easy way to upload new PO files, either automatically or manually.
- Free for open source projects.
- Ability to contribute changes back to this repository via a pull request.
  - I don't think we are allowed to give direct write-access to the platforms, so a PR will be ideal.

I think all of the ones listed above support these features.

I would like someone to evaluate the different platforms and some up with a suggestion for how we can use one. The goal is to make life easier for our translators.

**Comment by mgeisler** [comment]
@henrif75, we talked about this at some point in the past, but I figured we could try and crowd-source this.

**Comment by henrif75** [comment]
I put together a [simple spreadsheet](https://docs.google.com/spreadsheets/d/1uetSQ2zE-6YyKtqvZvE5gbS4qw4VrakRBMpNJr5Op-0/edit?usp=sharing) to collect the information.

**Comment by mgeisler** [comment]
Hi @henrif75, I talked with @guardsmanpanda today about this topic: Bjørn has been looking into this as well and I hope we can move forward with trying out one of the platforms.

@deavid, feel free to chime in if you have input as well :smile:

**Comment by GuardsmanPanda** [comment]
@deavid Later (this week I hope) I'll post some thoughts and a direction for further investigation / testing, but I am leaning towards suggesting that all translation work happens in the tool, it is much more convenient when sentences can be updated / approved individually.

But, there is still some thinking and tooling work to be done here, for example, right now the translation keys are just the English sentence, so even minor wording or grammar changes would be a 'new' translation key (save for some fancy matching magic), is that a problem we need to fix?

I am imagining the flow as follows.
1) Change to the course.
2) Push new phrases to the translation tool.
3) Update translations in the translation tool.
4) CI process rebuilds the course with the latest translation, grabbed directly from the tool API.

Not sure if step 2 happens auto magically or manually with human oversight, I lean towards the latter since I doubt we will make many course updates that break translations.

A major point is that the translation tool will / should be "round trip safe" so that we can always revert direction if something doesn't work.

**Comment by mgeisler** [comment]
> I am leaning towards suggesting that all translation work happens in the tool, it is much more convenient when sentences can be updated / approved individually.

Yeah, me too — with a translation platform, I don't think we need to commit the PO files any longer. We thus also don't need any PRs.

> But, there is still some thinking and tooling work to be done here, for example, right now the translation keys are just the English sentence, so even minor wording or grammar changes would be a 'new' translation key (save for some fancy matching magic), is that a problem we need to fix?

This solution came about because of two things:

* It's how Gettext works and I happened to know Gettext from the past.
* We need something very lightweight and un-intrusive in the Markdown. Having to create and maintain keys in the Markdown would be too complicated.

So to me, this is not a problem that needs fixing.

You mention fancy matching and infact, [`msgmerge`](https://www.gnu.org/software/gettext/manual/html_node/msgmerge-Invocation.html) will do such matching. It's not fancy by any means... but it is sometimes helpful :smile: What happens is that it

* Compares the `msgid` entries in an old translation (`xx.po`) with the authoratative `msgid` entries in a fresh `messages.pot` file.
* The `msgid` entries from the POT file correspond to the current English paragraphs — the `msgid` entries in the PO file correspond to what was current back when the translation was last updated.
* If `msgmerge` finds an old `msgid` entry in the PO file that looks similar to the `msgid` entry from the POT file, it will use the old translation for the new `msgid` key. It marks the whole thing as ["fuzzy"](https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html).

> Not sure if step 2 happens auto magically or manually with human oversight, I lean towards the latter since I doubt we will make many course updates that break translations.

We do seem to continue to update the text of the course, so if a translation wants to stay up to date, it would need to incorporate these changes. We do have a mechanism in place whereby we freeze a translation to the time it was last updated. This means that the Danish translation won't include new changes made today — and it thus has a chance of catching up.

I hope this is described okay in [TRANSLATIONS.md](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md).

**Comment by hwhsu1231** [comment]
I have published the [comprehensive-rust-l10n](https://github.com/localizethedocs/comprehensive-rust-l10n) project, which integrates with the [Crowdin](https://crowdin.com) platform. I believe this project could serve the purpose of this issue. See the [announcement](https://github.com/google/comprehensive-rust/discussions/3111) post on GitHub Discussions for more details.
