### ISSUE TITLE
es: Formatting errors in svgbob diagrams

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1329]
There are a few formatting problems in the svgbob diagrams in the Spanish translation. As an example, [16.2. Cadenas movidas en Rust](https://google.github.io/comprehensive-rust/es/ownership/moved-strings-rust.html) looks like this right now:

![image](https://github.com/google/comprehensive-rust/assets/89623/38cb335b-c0c0-4441-853c-e4284a84a034)

The problem is that [svgbob](https://ivanceras.github.io/content/Svgbob/Specification.html) isn't Markdown, so we cannot use emphasis here.

**Comment by mgeisler** [comment]
@deavid and @vzz1x2, could one of you take a quick look at this?

**Comment by carreter** [comment]
This still seems to be an issue:
![image](https://github.com/google/comprehensive-rust/assets/5355463/18ae4574-9c1f-487e-80e2-f3fc78d166f9)

I will take a crack at it as part of figuring out how the translation system works!
