### ISSUE TITLE
Remove inactive reviewers from `CODEOWNERS`

### ISSUE THREAD

**Issue by henrif75** [google/comprehensive-rust#1353]
@henrif75, related to this, I suggest we remove people from the `CODEOWNERS` file if we don't see them in ~3 months or so. That will help keep the list of reviewers focused and it will avoid the situation where everybody thinks someone else will deal with the review.

_Originally posted by @mgeisler in https://github.com/google/comprehensive-rust/issues/1343#issuecomment-1758523736_

**Comment by mgeisler** [comment]
I think this was done with #1386.

**Comment by henrif75** [comment]
I did some basic cleanup there, but didn't check inactive users.

**Comment by mgeisler** [comment]
Okay, I guess I would prefer closing this issue and then just do it every ~3 months or so if that's okay with you?
