### ISSUE TITLE
zh-CN: incorporate glossary

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1367]
I just found a [Simplified Chinese Rust glossary](https://github.com/rust-lang-cn/english-chinese-glossary-of-rust/blob/master/rust-glossary.md).

This could be useful as a starting point for translating https://google.github.io/comprehensive-rust/zh-CN/glossary.html.

Please feel free to merge in relevant words from the glossary — the glossary I created is only a start and we might want to add/remove words.

**Comment by mgeisler** [comment]
cc @SketchK, @wnghl and others who work on the Simplified Chinese translation.

**Comment by mgeisler** [comment]
Let me close this one again — if you feel the glossary should be updated, then please go ahead and create PRs for that.

**Comment by SketchK** [comment]
@mgeisler Hi, I saw this pr too late, but this glossary is awesome! 
I will do something to help our transation!
