### ISSUE TITLE
dprint-packages

### ISSUE THREAD

**Issue by javad-jafari** [google/comprehensive-rust#1383]
every time for formatting our `xx.po` we need to do` dprint fmt` ,this command always need strong proxy to execute correctly ! please make a easy way to achieve that @mgeisler .

**Comment by mgeisler** [comment]
Hi @javad-jafari, thanks for reporting this.

What do you mean by "strong proxy"?

If installing `dprint` is problematic, then you can use `msgcat` directly from the Gettext utilities.

You need to run

```
msgcat -o po/xx.po po/xx.po
```

to format the file (this is the command that `dprint` runs).

**Comment by mgeisler** [comment]
Please also see the discussion in #1394 if you are on Windows. You need to download the Gettext tools once and then you should be able to format your translation without any Internet connection (that applies to both Linux, MacOS, and Windows after installing `msgcat`).

If this is a general problem with `dprint`, then please open an issue in their repository: https://github.com/dprint/dprint.
