### ISSUE TITLE
Wrong speaker notes in "Compound types" chapter

### ISSUE THREAD

**Issue by Zlika** [google/comprehensive-rust#1412]
In the "Compound types" chapter, the speaker notes suggest:
`We could also have used {a} and {a:?} without specifying the value after the format string.`

This does not work on this code:
```
   Compiling playground v0.0.1 (/playground)
error[E0277]: `[i8; 10]` doesn't implement `std::fmt::Display`
 --> src/main.rs:4:18
  |
4 |     println!("a: {a}");
  |                  ^^^ `[i8; 10]` cannot be formatted with the default formatter
  |
  = help: the trait `std::fmt::Display` is not implemented for `[i8; 10]`
  = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
  = note: this error originates in the macro `$crate::format_args_nl` which comes from the expansion of the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground` (bin "playground") due to previous error
```

**Comment by Zlika** [comment]
Hi. I'm not a Rust expert, I'm just reading this training to learn Rust so I don't feel that I have enough knowledge on this topic to propose a (relevant) change.
From my point of view, there are 2 options to fix this problem:
* Remove the sentences using {a}.
* Add more info to explain why it was possible to use {x} in the "Small Example" page, and why it is not possible to use it here on arrays.

**Comment by mgeisler** [comment]
> Hi. I'm not a Rust expert, I'm just reading this training to learn Rust so I don't feel that I have enough knowledge on this topic to propose a (relevant) change.

That makes a lot of sense! Could you read over #1421 to let me know if it makes sense to you?

**Comment by Zlika** [comment]
> > Hi. I'm not a Rust expert, I'm just reading this training to learn Rust so I don't feel that I have enough knowledge on this topic to propose a (relevant) change.
> 
> That makes a lot of sense! Could you read over #1421 to let me know if it makes sense to you?

Great! Thanks!
