### ISSUE TITLE
How do I request external space permissions for my app and get a valid storage path?

### ISSUE THREAD

**Issue by Hope10086** [google/comprehensive-rust#1446]
I tried to save the OpenGL ES rendering results as png images, using a third-party library: [stb_image_write_rust](https://github.com/StbRust/stb_image_write_rust), but it showed read-only system when executing the file creation by
```
impl ImageWriter {
    pub fn new(path: &str) -> ImageWriter {
        ImageWriter {
            file: File::create(path).expect("could not create file"),
        }
    }
```
`Logcat:   panicked at 'could not create file: Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }', C:\Users\Zhang\.cargo\git\checkouts\stb_image_write_rust-e6019e676b2d2614\c748c62\stb_image_write_rust\src\ImageWriter.rs:12:38`

How can we solve this problem?

**Comment by mgeisler** [comment]
Hi @Hope10086, I don't think this question is about the Rust course maintained in this repository — I suggest you ask it in https://users.rust-lang.org/ instead.

**Comment by mgeisler** [comment]
I'll close this for now — feel free to leave a comment if it's somehow related to our Rust course after all.
