### ISSUE TITLE
Translation impact of v2 changes

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1463]
# Head of `main`

Looking only at the translations linked in our language picker, I see these numbers right now using `main`:

```
pt-BR before: 1597 translated messages, 196 fuzzy translations, 727 untranslated messages.
zh-CN before: 1634 translated messages, 193 fuzzy translations, 693 untranslated messages.
zh-TW before: 1505 translated messages, 137 fuzzy translations, 878 untranslated messages.
ko before: 1968 translated messages, 204 fuzzy translations, 348 untranslated messages.
es before: 2018 translated messages, 112 fuzzy translations, 390 untranslated messages.
```

This is after updating the translations with the newest strings from `main`:

```sh
MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot"}}' mdbook build -d po
for lang in pt-BR zh-CN zh-TW ko es; do
    msgmerge --update po/$lang.po po/messages.pot
    echo -n "$lang before: "; msgfmt -o /dev/null --stat po/$lang.po
done
```

# Head of `cr2-organization`

Updating to 9dcb262 on `cr2-organization` and running the same commands will show the impact of the branch in terms of messages that have been touched. I get these numbers:

```
pt-BR after: 1086 translated messages, 351 fuzzy translations, 1148 untranslated messages.
zh-CN after: 1160 translated messages, 320 fuzzy translations, 1105 untranslated messages.
zh-TW after: 1019 translated messages, 281 fuzzy translations, 1285 untranslated messages.
ko after: 1453 translated messages, 377 fuzzy translations, 755 untranslated messages.
es after: 1530 translated messages, 274 fuzzy translations, 781 untranslated messages.
```

In table form:

| Language | Translated before | %   | Translated after | %   |
|----------|-------------------|-----|------------------|-----|
| pt-BR    | 1597              | 63% | 1086             | 42% |
| zh-CN    | 1634              | 65% | 1160             | 45% |
| zh-TW    | 1505              | 60% | 1019             | 39% |
| ko       | 1968              | 78% | 1453             | 56% |
| es       | 2018              | 80% | 1530             | 59% |

This suggests that the new material touch about 500 messages, or 1/3 of the content.

# Using back-dated sources

Now, the above shows the raw delta between `main` and `cr2-organization`. The actual impact on the translations will be different: the translations are published using back-dated sources, sources that match the time of the last `msgmerge`.

The statistics for the translations right now (using back-dated sources) is:

| Language | Translated now | %   |
|----------|----------------|-----|
| pt-BR    | 1762           | 71% |
| zh-CN    | 1658           | 67% |
| zh-TW    | 1644           | 66% |
| ko       | 2175           | 88% |
| es       | 2101           | 86% |

# Risks

When we introduced the snapshot publishing system in #1243, we also created a risk that a translation will stay behind forever.

I wonder if translations will chose to not jump past the merge point with `cr2-organization`?

We can mitigate this by having our internal Localization team work on updating the translations after the merge.

**Comment by mgeisler** [comment]
cc @henrif75, @djmitche, @kantasv, @deavid, @jiyongp, @victorhsieh, @Phosphorus-M, @nodmp, etc...

**Comment by henrif75** [comment]
I think using the localization team is the fastest way to have the translations on v2 asap. However, we will need to give a heads up to reviewers to get a fast turnaround.

**Comment by mgeisler** [comment]
> I think using the localization team is the fastest way to have the translations on v2 asap. However, we will need to give a heads up to reviewers to get a fast turnaround.

Yes, I agree! Nothing should break after the merge, but I agree that we should engage with the Localization team to have this translated then.

**Comment by mgeisler** [comment]
I just ran `msgmerge --update` on the languages mentioned above and the result is [v2-po-files.zip](https://github.com/google/comprehensive-rust/files/13366469/v2-po-files.zip).

I think it would be nice to send these to the Localization team already now. @henrif75, if you split them into days, I would ask the team to translate Day 1 to 3 first. When the PR is merged, you should be able to run `mdbook-xgettext` to extract the messages again, do another `msgmerge --update` and send this out for review.

**Comment by henrif75** [comment]
> I just ran `msgmerge --update` on the languages mentioned above and the result is [v2-po-files.zip](https://github.com/google/comprehensive-rust/files/13366469/v2-po-files.zip).
> 
> I think it would be nice to send these to the Localization team already now. @henrif75, if you split them into days, I would ask the team to translate Day 1 to 3 first. When the PR is merged, you should be able to run `mdbook-xgettext` to extract the messages again, do another `msgmerge --update` and send this out for review.

SG, I'll start preparing the files and send the translation requests.

**Comment by Phosphorus-M** [comment]
If we want to update the translation, we do a PR into the fork of @djmitche?
I mean an update of the translation using the new branch.

**Comment by mgeisler** [comment]
> If we want to update the translation, we do a PR into the fork of @djmitche? I mean an update of the translation using the new branch.

Hi @Phosphorus-M! Sorry for the slow reply... It's so cool that you're eager to help out :smile: The branch has just been merged, so you can follow the usual procedure for refreshing a translation: `mdbook-xgettext` followed by `msgmerge`!

**Comment by henrif75** [comment]
> > I just ran `msgmerge --update` on the languages mentioned above and the result is [v2-po-files.zip](https://github.com/google/comprehensive-rust/files/13366469/v2-po-files.zip).
> > I think it would be nice to send these to the Localization team already now. @henrif75, if you split them into days, I would ask the team to translate Day 1 to 3 first. When the PR is merged, you should be able to run `mdbook-xgettext` to extract the messages again, do another `msgmerge --update` and send this out for review.
> 
> SG, I'll start preparing the files and send the translation requests.

@mgeisler Congrats on the v2 launch!
I'll start extracting the `.po` files and send to the localization team, prioritizing first the "officially" published translations (e.g., KR) - except the Spanish (thanks @Phosphorus-M, I'll wait for your PRs!)

**Comment by mgeisler** [comment]
Thanks @henrif75, that sounds perfect!

**Comment by henrif75** [comment]
I've sent the KR (#262 ) translation to the localization team.

**Comment by henrif75** [comment]
zh-CN (#324) translation sent to localization.

**Comment by mgeisler** [comment]
I'm biting the bullet now and have been sending out PRs to update all translations to include the new entries:


- #1737
- #1738
- #1739
- #1740
- #1741
- #1742
- #1743
- #1744
- #1745
- #1746
- #1748
- #1749
- #1750
- #1751
- #1752

I skipped a few langauges since they were already under heavy work via translations merged in by @henrif75 and others.

**Comment by mgeisler** [comment]
Hi @henrif75, would you like to keep this issue open until the published translations are updated, or can we close it now?

**Comment by henrif75** [comment]
> Hi @henrif75, would you like to keep this issue open until the published translations are updated, or can we close it now?

As soon we finish the Japanese translation I can close this issue, thanks.

**Comment by mgeisler** [comment]
> As soon we finish the Japanese translation I can close this issue, thanks.

@henrif75, did we update the translation?

**Comment by henrif75** [comment]
> > As soon we finish the Japanese translation I can close this issue, thanks.
> 
> @henrif75, did we update the translation?

Oh we did, I'm closing it!

**Comment by mgeisler** [comment]
Thanks a lot!
