### ISSUE TITLE
"Out-of-bounds access" bug is incorrect

### ISSUE THREAD

**Issue by Enes1313** [google/comprehensive-rust#1475]
I think "Out-of-bounds access" bug in the speaker notes section on [speaker notes section on "An Example in C"](https://google.github.io/comprehensive-rust/why-rust/an-example-in-c.html#speaker-notes) is incorrect. C standards (C89/90 to C23) says "argv[argc] shall be a null pointer.". For example: [C11 5.1.2.2.1 Program startup P2](https://port70.net/~nsz/c/c11/n1570.html#5.1.2.2.1p2) There is only a logical error here. "Unchecked return values of stat and fopen (lines 18 and 26)" covers this error. 

In addition, about ```len = st.st_size;``` (line 19):

"st.st_size" is indeterminate value if the stat function does not write anything to the address of st (ex. filename = NULL)

* [using indeterminately-valued objects](https://port70.net/~nsz/c/c89/c89-draft.html#1.6) (st.st_size) is undefined behavior in C89/90
* There is UB If type of "st.st_size" has [trap representation](https://port70.net/~nsz/c/c99/n1256.html#6.2.6.1p5), else it's value is unspecified in C99. Since [the address of st is used and storage duration of st is automatic](https://port70.net/~nsz/c/c11/n1570.html#6.3.2.1p2), the same rule applies for C11. 
* Since C23, the only representation allowed is two's complement for signed integer. I don't know if the above situation is unspecified in the C23 standard.

Briefly:

No "Out-of-bounds access"
Reading uninitialized variable (line 19)

What do you think? @mgeisler

**Comment by mgeisler** [comment]
> I'm pretty uncomfortable with this slide anyway, especially in the hello-world section. Many students aren't C++ programmers, and even many who are probably aren't familar enough with C to have this slide be helpful.

I think it was @randomPoison who gave similar feedback... I would actually be okay with dropping the slide again (sorry @ColinFinck!). Or at least move the content into speaker notes on some other slide. It unfortunately assumes too much C knowledge for our typical audience.

**Comment by Enes1313** [comment]
> I'm pretty uncomfortable with this slide anyway, especially in the hello-world section. Many students aren't C++ programmers, and even many who are probably aren't familar enough with C to have this slide be helpful.
> 
> Could this slide be shrunk down to something much more succinct? Maybe the list in "Isn’t this a highly unrealistic example?" could be the entirety of the slide, with the speaker notes highlighting that Rust is designed to catch common errors -- which can and do turn into security vulnerabilities -- at compile time.

Yes, I agree. I don't know how effective my opinion on this subject will be, but: even though it's kind of nice to compare it to C. It seems bad that it is based on an example.

**Comment by ColinFinck** [comment]
@Enes1313: Thank you very much for your research! I have indeed missed these details.

@djmitche @mgeisler: Feel free to alter the slide to your needs or leave it out entirely.
I was under the impression that a majority of the audience has a strong C / C++ background -- especially taking into account that Martin talked about training some Android programmers to rewrite C / C++ libraries in Rust.
From my experience, die-hard C / C++ programmers are hard to convince to change their habits. Talk is cheap, but actual example code works wonders here. Which was my reason to come up with that example in the first place.
Your mileage may vary though. I wonder if we find a way to tailor the course to both die-hard C / C++ programmers as well as students coming from other programming languages (or even students without any prior programming experience?)

**Comment by mgeisler** [comment]
> I was under the impression that a majority of the audience has a strong C / C++ background -- especially taking into account that Martin talked about training some Android programmers to rewrite C / C++ libraries in Rust.

You're right that many of the people who take the course have a C/C++ background. It varies from class to class. Overall, I think it might be 30-50% of the participants who have a really strong C/C++ background — it's much more when we teach the bare-metal class.

Given this discussion, could one of you put up a PR to revert #1241 and instead add a link to the example in the speaker notes? @djmitche, I assume it's easy enough for you to rebase #1073  on top of such a PR, right?

**Comment by djmitche** [comment]
Yeah, no problem.

**Comment by Enes1313** [comment]
> > I was under the impression that a majority of the audience has a strong C / C++ background -- especially taking into account that Martin talked about training some Android programmers to rewrite C / C++ libraries in Rust.
> 
> You're right that many of the people who take the course have a C/C++ background. It varies from class to class. Overall, I think it might be 30-50% of the participants who have a really strong C/C++ background — it's much more when we teach the bare-metal class.
> 
> Given this discussion, could one of you put up a PR to revert #1241 and instead add a link to the example in the speaker notes? @djmitche, I assume it's easy enough for you to rebase #1073 on top of such a PR, right?

I can revert it if it's okay?

1- "Out-of-bounds access" bug will be deleted
2- "Variable can be read uninitialized." bug will be added

I didn't understand "... instead add a link to the example ..." part, sorry. Which link?

**Comment by mgeisler** [comment]
> I didn't understand "... instead add a link to the example ..." part, sorry. Which link?

Yeah, sorry, I see now that I wrong about this. I thought the link in [An Example in C](https://google.github.io/comprehensive-rust/credits.html#an-example-in-c) to the [Master Thesis](https://colinfinck.de/Master_Thesis_Colin_Finck.pdf) would show the example that we're removing. However, I can actually not find the code in the thesis, and I see now that the credits page says that the code is from the slides used by the presentation of the thesis.

So let's just revert the PR and perhaps we can add a link to a relevant example later.

**Comment by mgeisler** [comment]
Thanks for brinking this up @Enes1313 and for making the PR to take out the page.
