### ISSUE TITLE
Variant payload: "The pattern binds _references_ to the fields"

### ISSUE THREAD

**Issue by proski** [google/comprehensive-rust#1491]
https://google.github.io/comprehensive-rust/enums/variant-payloads.html

> The values in the enum variants can only be accessed after being pattern matched. The pattern binds references to the fields in the “match arm” after the =>. 

That sounds wrong to me. The variables used in `match` capture the enum contents. References can be requested using the `ref` keyword, but it's not used in the example.

Here's a slightly modified example (added `Box` and another `match`) that won't compile precisely because the binding is a move, not a borrow by default.

```
enum WebEvent {
    PageLoad,                 // Variant without payload
    KeyPress(Box<char>),      // Tuple struct variant
    Click { x: i64, y: i64 }, // Full struct variant
}

#[rustfmt::skip]
fn inspect(event: WebEvent) {
    match event {
        WebEvent::PageLoad       => println!("page loaded"),
        WebEvent::KeyPress(c)    => println!("pressed '{c}'"),
        WebEvent::Click { x, y } => println!("clicked at x={x}, y={y}"),
    }
    match event {
        WebEvent::PageLoad       => println!("page loaded"),
        WebEvent::KeyPress(c)    => println!("pressed '{c}'"),
        WebEvent::Click { x, y } => println!("clicked at x={x}, y={y}"),
    }
}

fn main() {
    let load = WebEvent::PageLoad;
    let press = WebEvent::KeyPress(Box::new('x'));
    let click = WebEvent::Click { x: 20, y: 80 };

    inspect(load);
    inspect(press);
    inspect(click);
}
```

**Comment by mgeisler** [comment]
The page is now at https://google.github.io/comprehensive-rust/pattern-matching/destructuring.html.

> That sounds wrong to me. The variables used in `match` capture the enum contents. References can be requested using the `ref` keyword, but it's not used in the example.

You are correct! When the `match` is done against an owned type, then the match arms move the values away from you. However, (and this changed in [Rust 2018](https://rust-lang.github.io/rfcs/2005-match-ergonomics.html)) with "match ergonomics", the args will actually give borrowed types if the `match` is done against a borrowed type.

So if we modify your great example to use `match &event`, then we'll see that `x`, and `y` are borrowed types.

We should add a line about this to the notes.
