### ISSUE TITLE
"Pattern Matching" doesn't mention ref and mut keywords

### ISSUE THREAD

**Issue by djmitche** [google/comprehensive-rust#1514]
In fact, it glosses over a lot of the subtleties of how references are handled in patterns. Maybe we can return to that in the "borrowing" section, later?

**Comment by mgeisler** [comment]
> In fact, it glosses over a lot of the subtleties of how references are handled in patterns. Maybe we can return to that in the "borrowing" section, later?

I would at most mention this in the notes: I consider `ref` and `mut` old-fashioned with the match ergonomics we get as part of Rust 2018 (or 2021? I forget).

That is, for a bootcamp style class like ours, we can only hope to

- make people comfortable with the idea of taking values apart with pattern matching
- we also explain how the bindings are references to the individual parts

That's about it. I've sometimes done some adhoc examples with `ref`, but only occasionally.

**Comment by djmitche** [comment]
It looks like #1663 addressed this!
