### ISSUE TITLE
Look into publishing PDFs with mdbook-typst

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1543]
There is a new tool which can convert an mdbook to Typst format, and thus also to high-quality PDFs: https://github.com/LegNeato/mdbook-typst

**Comment by LegNeato** [comment]
This exposed some bugs in my libraries, thanks! Attached is a generated PDF with the unreleased changes. Obviously there is more work to do, and I haven't yet styled on the typst side so presentation is lacking.

[book.pdf](https://github.com/google/comprehensive-rust/files/13529697/book.pdf)

The TOC and headings and stuff are a bit wonky as I tuned the heuristics on the mdBook guide. That area is pretty hacky and I am going to be beefing it up in the coming weeks so it works for most / all cases.

There are escape hatches that let you directly insert typst markup before and after `mdbook-typst` does it's thing. That is a potential stop gap solution if you can't find time to contribute improvements directly yet still want to tweak the output.

**Comment by mgeisler** [comment]
Yeah, wow, thank you for producing this!

People have asked for a PDF version once or twice — I suggest we publish this when we publish the course and replace the print page with a link directly to the PDF.

**Comment by max-heller** [comment]
Sorry to hijack this thread, but it seems to be gaining traction: I recently released a similar tool, [`mdbook-pandoc`](https://crates.io/crates/mdbook-pandoc), that can generate PDFs (and other formats) using [`pandoc`](https://pandoc.org/). It doesn't have the potential to be 100% Rust that `mdbook-typst` has, but seems more mature at the moment. [Here's a PDF of the book](https://github.com/google/comprehensive-rust/files/13536628/Comprehensive.Rust.pdf) generated with the following config:

```toml
[output.pandoc.profile.pdf]
output = "Comprehensive Rust.pdf"
pdf-engine = "lualatex"
```

Two notes on generating the book:

- I had to comment out the badges in `src/index.md` since pandoc doesn't know what to do with them--it usually handles remote images well, but I think the non-image extensions (e.g. `.yml` are confusing it):

  ```diff
  diff --git a/src/index.md b/src/index.md
  index bcff48c..d35360d 100644
  --- a/src/index.md
  +++ b/src/index.md
  @@ -1,8 +1,10 @@
   # Welcome to Comprehensive Rust 🦀
  
  +<!--
   [![Build workflow](https://img.shields.io/github/actions/workflow/status/google/comprehensive-rust/build.yml?style=flat-square)](https://github.com/google/comprehensive-rust/actions/workflows/build.yml?query=branch%3Amain)
   [![GitHub contributors](https://img.shields.io/github/contributors/google/comprehensive-rust?style=flat-square)](https://github.com/google/comprehensive-rust/graphs/contributors)
   [![GitHub stars](https://img.shields.io/github/stars/google/comprehensive-rust?style=flat-square)](https://github.com/google/comprehensive-rust/stargazers)
  +-->
  
   This is a free Rust course developed by the Android team at Google. The course covers
   the full spectrum of Rust, from basic syntax to advanced topics like generics
  ```

- The book contains unicode characters that the default LaTeX font doesn't support (e.g. 🦀), so you may want to [swap out the fonts](https://pandoc.org/MANUAL.html#fonts).

**Comment by LegNeato** [comment]
Awesome, that looks great!

**Comment by mgeisler** [comment]
Thanks for posting this @max-heller! Seeing the course in this form makes me nostalgic for my old university days!

I don't have a lot of bandwidth to experiment with this right now, but I would be supportive of us publishing a PDF along with the HTML. It's probably just a matter of adding a few lines to our `publish.yml` file.

**Comment by mgeisler** [comment]
> > I don't have a lot of bandwidth to experiment with this right now, but I would be supportive of us publishing a PDF along with the HTML. It's probably just a matter of adding a few lines to our `publish.yml` file.
> 
> Shouldn't it be able to be built into the `/book` directory and then linked in the html template instead of the browser print dialogue if that value is set in the `book.toml`? At least this would be what I would expect from a rendered pdf.

Right, I think I agree: we can remove the :printer: button from the pages and instead link to the PDF.
 
> Unfortunately that is less mobile compatible: https://caniuse.com/?search=pdf as fewer browsers seems to have a built-in pdf viewer. :/

If the `print.html` page is no longer generated, then I suppose people lose a way of easily getting a concatenated version of the _HTML_ for the course. A PDF would be a concatenated version, but it would of course look different.

I don't think much is lost if we don't link to `print.html` and replace it with a well-formatted PDF.

> The alternative could be to introduce another link on the top menu right-hand side for opening it as a pdf-book, or an `Export` dropdown where different rendered books are mentioned. pdf and epub for example.

I would prefer to add a new page in the course which links to the PDF (and perhaps other formats if we generate those). Horizontal space is a costly resource, so this would allow us to remove the :printer: icon on every page.

**Comment by mgeisler** [comment]
> Yes, although it would be interesting to keep the print button and create a modal when clicking on it with an overview of all possible `print-friendly` resources of the book, including `pdf`.

That sounds somewhat complicated :slightly_smiling_face:  — the course doesn't have a dedicated web developer associated with it, so it would likely be me who would maintain this.

> Though I would say, that it would be more intriguing to optimize the `mdbook` themes for mobile friendliness.

Similarly, while this is a great goal, it is unfortunately outside the scope of what I can do on the course. In general, `mdbook` seems like a project that could use more resources. It's become an essential part of the Rust ecosystem, but I think there is only a tiny developer community around it.

**Comment by mgeisler** [comment]
Thanks to the work of @max-heller, high-quality PDFs are now published on every merge to `main`! See https://google.github.io/comprehensive-rust/comprehensive-rust.pdf for the English one. They are generated with LaTeX and they're generated for all languages.

There are a few things to fix (emojis are not rendered), but I think the result looks very nice already. I suggest we try fixing the emojis and then start linking to the PDFs.

**Comment by mgeisler** [comment]
Thanks @max-heller for implementing this, people are liking it a lot on Mastodon: https://elk.zone/ohai.social/@mgeisler/112054837248737025 🙂

**Comment by simonsan** [comment]
This is really awesome! Would be cool actually, to have some easy to follow instructions how to do that for mdbooks in general. Would like to spread that knowledge a bit.

**Comment by max-heller** [comment]
> This is really awesome! Would be cool actually, to have some easy to follow instructions how to do that for mdbooks in general. Would like to spread that knowledge a bit.

[The README for `mdbook-pandoc`](https://github.com/max-heller/mdbook-pandoc) talks about how to get started. It doesn't go into details of what was needed for Comprehensive Rust (fallback fonts, translation, etc.) so it could probably use some fleshing out.

**Comment by simonsan** [comment]
> > This is really awesome! Would be cool actually, to have some easy to follow instructions how to do that for mdbooks in general. Would like to spread that knowledge a bit.
> 
> [The README for `mdbook-pandoc`](https://github.com/max-heller/mdbook-pandoc) talks about how to get started. It doesn't go into details of what was needed for Comprehensive Rust (fallback fonts, translation, etc.) so it could probably use some fleshing out.

Would you be able to help us to get started over at https://github.com/rust-unofficial/patterns/issues/380 to set that up for the Rust Patterns book? 😬

**Comment by max-heller** [comment]
> Would you be able to help us to get started over at [rust-unofficial/patterns#380](https://github.com/rust-unofficial/patterns/issues/380) to set that up for the Rust Patterns book? 😬

https://github.com/rust-unofficial/patterns/pull/394

**Comment by simonsan** [comment]
> * The book contains unicode characters that the default LaTeX font doesn't support (e.g. 🦀), so you may want to [swap out the fonts](https://pandoc.org/MANUAL.html#fonts).

@max-heller Do you have any recommendation there which work well with unicode characters from your own experience?

**Comment by max-heller** [comment]
> Do you have any recommendation there which work well with unicode characters from your own experience?

Depends a lot on which characters are needed in which contexts, unfortunately there's no mega font that includes every single glyph. For this book, we added Noto Color Emoji, Noto Sans Math, and Noto CJK fonts as necessary for non-English characters:

https://github.com/google/comprehensive-rust/blob/c633f85f5739b17a764d30e8fa94b3219f14d73b/book.toml#L37-L42
