### ISSUE TITLE
GUI Exercise is more about text formatting than trait objects

### ISSUE THREAD

**Issue by djmitche** [google/comprehensive-rust#1617]
This is from feedback in #1565. It is in the "Methods and Traits" segment, so it doesn't necessarily need to focus on trait objects. But, something nifty with traits would be good.

I've not come up with a great idea yet. The best I've got is some kind of signal-processing DAG, like old-school analog synthesizers. So you'd have a few types that take `dyn SignalSource` trait objects, and themselves implement `SignalSource`. But, signal processing is a little complex for an example!

I'm open to ideas here!

**Comment by mgeisler** [comment]
> GUI Exercise is more about text formatting than trait objects

I agree... even though I love making this kind of formatting myself, it's not the right focus for this exercise.

**Comment by djmitche** [comment]
Per #1516, this is a little too early for trait objects anyway, so let's think of something that just requires traits.

**Comment by djmitche** [comment]
I think the simplest will be something where generics are used to support dependency injection. Something like

```
pub trait Storage {
    fn put(&mut self, k: String, v: String);
    fn get(&self, k: &str) -> Option<&str>;
}

pub struct InMemoryStorage;

impl Storage for InMemoryStorage { .. }

pub struct OnDiskStorage;

impl Storage for OnDiskstorage { .. }

fn uses_storage<S: Storage>(storage: S) {
  storage.put(..);
  // ...
}
```

**Comment by djmitche** [comment]
Unfortunately, the modules segment depends on this one, suggesting breaking it up into modules. Maybe that's OK? Maybe the exercise for that segment is "here's some code you haven't seen before, put it into modules" instead of "here's some code you worked on yesterday, .."? Being able to read Rust code is a good skill to practice, and that's probably a good segment to practice it in..
