### ISSUE TITLE
Miss type, miss spell

### ISSUE THREAD

**Issue by kariyum** [google/comprehensive-rust#1633]
In chapter 1, type-and-values, exercise section, the sentence says, "For n>2, **he** n'th Fibonacci ..." **"the"** is miss spelled, it is spelled **"he"** instead.

**Comment by djmitche** [comment]
Thanks :)

**Comment by kariyum** [comment]
That was fast, I thought about creating a PR, but I had to leave for a few minutes😅. Thank you!

**Comment by djmitche** [comment]
lol, sorry, and thanks :)
