### ISSUE TITLE
Ambiguous "pointers to data on the stack"

### ISSUE THREAD

**Issue by proski** [google/comprehensive-rust#1677]
https://google.github.io/comprehensive-rust/async/pitfalls/pin.html

I realize it's a complex topic, but would it be possible to use more clear language for the text that is already there?

> When you await a future, all local variables (that would ordinarily be stored on a stack frame) are instead stored in the Future for the current async block.

Why is the second "Future" capitalized?

Is it correct that the first future that the second future are different?

> If your future has pointers to data on the stack, those pointers might get invalidated.

This can be interpreted in two ways:

* The future has pointers on the stack. Those pointers point to some data.
* The future has pointers. Those pointers point to data on the stack.

How can the pointers get invalidated? Does the execution continue with the stack at a different address? Does some other code have write access to the future as it's awaiting?

> This is unsafe.

Maybe it should be written as "This would be unsafe" as it not a real danger for safe Rust code.

> Therefore, you must guarantee that the addresses your future points to don’t change.

This probably rules out the stack at a a different address, but I'm guessing here.

Who is that mischievous monkey that tries to move objects around?

> That is why we need to “pin” futures.

Looking at the example, it's the future we call (`timeout_fut`) that needs to be pinned. Yet its address is in the `worker()` scope. So it's not the case of a future that has pointers and needs to be pinned. One future has pointers (our code) but we are pinning another future (`timeout_fut`).

> Using the same future repeatedly in a select! often leads to issues with pinned values.

That's vague and scary. I think it means that the future cannot be replaced with another one and needs to be reset in place if possible. Thankfully, `tokio::time::sleep` can be `reset`. That could be mentioned in the notes below.

**Comment by djmitche** [comment]
Thanks! These are good comments! I've got a bunch of issues like this to work through so this will go on the list. If you'd like to make a PR to fix this, that would be ❤️

**Comment by djmitche** [comment]
Solved in #1687.
