### ISSUE TITLE
Fix rendering of emojis in PDFs

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1708]
With #1572 merged, we now publish [`comprehensive-rust.pdf`](https://google.github.io/comprehensive-rust/comprehensive-rust.pdf). Emojis are not rendered correctly right now:

![image](https://github.com/google/comprehensive-rust/assets/89623/a9e9b61b-3861-4f1e-bf00-75df632ff00e)

This also results in huge logs being produced when running `mdbook build`, as can be seen in [this GH action run](https://github.com/google/comprehensive-rust/actions/runs/7534384470/job/20508683090).

I'm happy to remove the :crab: from the course title, but I think we still need to be able to render some emojis in the PDFs.

**Comment by mgeisler** [comment]
@max-heller, if you have ideas here, then I would love to hear them :smile:

**Comment by max-heller** [comment]
The main Noto fonts don't contain emojis so LaTeX needs to be told to fall back to the variant that does. Two reasonable-looking solutions: [1](https://eskola.uk/2021/pandoc-latex-font-fallback/) [2](https://tex.stackexchange.com/questions/685097/emojis-with-lualatex/685101#685101)

**Comment by mgeisler** [comment]
Thanks for the investigation! I'll leave it to you or someone else to look further into this.

**Comment by max-heller** [comment]
https://github.com/jgm/pandoc/pull/9204 would make it easy to add fallback fonts for emoji
