### ISSUE TITLE
Lines not wrapping in PDF tables

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1709]
The Android [Build Rules](https://google.github.io/comprehensive-rust/android/build-rules.html) chapter has a table with text which should wrap. The [PDFs](https://google.github.io/comprehensive-rust/comprehensive-rust.pdf) currently don't wrap the lines:

![image](https://github.com/google/comprehensive-rust/assets/89623/ce0425f0-5a89-44b1-ab87-d8e2e0421e64)

I like the LaTeX environment used for the table a lot, we just need to extend it a bit to support wrapped text.

Cc @max-heller.

**Comment by max-heller** [comment]
[This is a known issue](https://github.com/max-heller/mdbook-pandoc#known-issues). LaTeX will wrap the contents of cells if given relative widths to constrain each column. Pandoc sets these widths if its standard markdown parser is used but not if its Commonmark parser is used (see https://github.com/jgm/commonmark-hs/issues/128).

As a workaround, it should work to write a Pandoc filter that sets the [width for each column](https://hackage.haskell.org/package/pandoc-types-1.23.1/docs/Text-Pandoc-Definition.html#t:ColSpec) to 1/n (n being the number of columns), though this will force tables that could be represented more compactly to take up the full width of the page

**Comment by mgeisler** [comment]
> [This is a known issue](https://github.com/max-heller/mdbook-pandoc#known-issues).

Ah, thanks, I hadn't looked there!

> LaTeX will wrap the contents of cells if given relative widths to constrain each column.

Yes, I remember being able to control the column widths back in the day when writing LaTeX directly. It's been several years, but I still have the good old LaTex Companion somewhere :smile: 

> As a workaround, it should work to write a Pandoc filter that sets the [width for each column](https://hackage.haskell.org/package/pandoc-types-1.23.1/docs/Text-Pandoc-Definition.html#t:ColSpec) to 1/n (n being the number of columns), though this will force tables that could be represented more compactly to take up the full width of the page

Nice idea! Would it also be possible to embed a small "language" for this in a HTML comment in the Markdown? If a Pandoc filter has access to this, then that could be a nice way to do it:

```markdown
<!-- Pandoc columns: default 0.8 -->

| Module Type    | Description                                                             |
|----------------|-------------------------------------------------------------------------|
| `rust_binary`  | Produces a Rust binary.                                                 |
| `rust_library` | Produces a Rust library, and provides both `rlib` and `dylib` variants. |
```

could perhaps be parsed and used to attach a `ColWidthDefault` and `ColWidth 0.8` value to each column?

**Comment by max-heller** [comment]
> Nice idea! Would it also be possible to embed a small "language" for this in a HTML comment in the Markdown? If a Pandoc filter has access to this, then that could be a nice way to do it:
> 
> ```
> 
> 
> | Module Type    | Description                                                             |
> |----------------|-------------------------------------------------------------------------|
> | `rust_binary`  | Produces a Rust binary.                                                 |
> | `rust_library` | Produces a Rust library, and provides both `rlib` and `dylib` variants. |
> ```
> 
> could perhaps be parsed and used to attach a `ColWidthDefault` and `ColWidth 0.8` value to each column?

That sounds like it'd work, the HTML comment should be included in the Pandoc AST

**Comment by mgeisler** [comment]
Okay, cool! I don't know if there is precedent for "smuggling" information through like that in Pandoc?

We've done something very similar for the text extraction in `mdbook-xgettext`: there you can add `<!-- mdbook-xgettext:skip -->` to [skip the next block](https://github.com/google/mdbook-i18n-helpers/blob/main/i18n-helpers/USAGE.md#marking-sections-to-be-skipped-for-translation).

**Comment by max-heller** [comment]
> I don't know if there is precedent for "smuggling" information through like that in Pandoc?

There are a lot of [examples](https://github.com/pandoc/lua-filters) out there, I'm sure someone's implemented something similar

**Comment by mgeisler** [comment]
Nice!

I won't be putting a lot of work into this myself, so the issue is here in case someone else finds the time to work on this. I can ask internally if someone wants to contribute their 20% time to it.
