### ISSUE TITLE
Show/hide the sizing box without re-running `mdbook`

### ISSUE THREAD

**Issue by djmitche** [google/comprehensive-rust#1796]
#1464 describes a way to enable a red box in development mode, to determine whether a slide will fit onscreen without scrolling.

Let's define a keystroke or hidden button that will toggle this box, without any special configuration in `book.toml`.  This will make it easier to use this tool while developing or reviewing a PR, without accidentally committing changes to `book.toml`.

CC @mani-chand who is working on fixing slides for #1464.

**Comment by djmitche** [comment]
@mani-chand, would you like to work on this? I don't know what your familiarity is with JS and web development.

**Comment by mani-chand** [comment]
> @mani-chand, would you like to work on this? I don't know what your familiarity is with JS and web development.

I will try and see.

**Comment by mani-chand** [comment]
> > @mani-chand, would you like to work on this? I don't know what your familiarity is with JS and web development.
> 
> Hey @djmitche , I haven't seen this comment till now.I will try and see if I can fix it. Don't assign  it to me now. Once I fix it I will directly make a PR. 

I am good react but don't know to work with scripts.

**Comment by djmitche** [comment]
Please be careful with editing comments, as it makes it hard to read the issue later!

**Comment by djmitche** [comment]
Sounds good. There's no React in use here, just plain old JavaScript. Perhaps someone else can pick this up!

**Comment by mani-chand** [comment]
Ok thank you. I am sure gonna give a try.

**Comment by mani-chand** [comment]
![google-hideshow](https://github.com/google/comprehensive-rust/assets/65899331/e429a2dc-13a0-4f7a-bdab-0212367184c2)

Hello @djmitche , Is this what you mean to do. Is it good or not . Any changes required.

**Comment by djmitche** [comment]
Not quite! #1464 has some screenshots of a dotted red box that shows the content that will fit on one screen while teaching the class. I'd like to reproduce that, but triggered with a keystroke or button click instead of a change to book.toml.

**Comment by mani-chand** [comment]
Okay ,I will check with that .

**Comment by mani-chand** [comment]
I need help how to get red box .

**Comment by mani-chand** [comment]
Hello @djmitche , I am not sure that we can hide that red box area because its  just a css fixed position. I am not sure how to explain it. But when tried to hide that just red box is hiding. When I have checked `book.toml` its div is empty. I am not sure how to work with it. I wrote the code at `theme/book.js`. Remove 2 comments "./aspect-ratio-helper" in `book.toml`. 
Code, I wrote.
```javascript,editable
var isHide = false;
    var hideShowButton = document.createElement('button');
    hideShowButton.className = (isHide ?"hide":"show");
    hideShowButton.title = (isHide?"Hide":"Show");
    hideShowButton.style.width = "50px"
    hideShowButton.style.display = "block"
    hideShowButton.style.textItem = "left";
    hideShowButton.innerHTML = (isHide?"Show":"Hide");
    hideShowButton.style.height = "25px"
    var preTag = document.getElementsByTagName('details');
    console.log(preTag[0]);
    preTag[0].insertBefore(hideShowButton, preTag[0].firstChild);

    function toggleContent() {
        //console.log("Toggling content",document.getElementsByClassName('playground')[0].children[1].hidden);
        if(document.getElementById('aspect-ratio-helper').hidden){
            document.getElementById('aspect-ratio-helper').hidden = false;
            hideShowButton.innerHTML = "Show";
            isHide=false;
            document.getElementById('aspect-ratio-helper').style.display = "none";
            hideShowButton.className="hide";
        }else{
            document.getElementById('aspect-ratio-helper').hidden = true;
            hideShowButton.innerHTML = "Hide";
            isHide=true;
            document.getElementById('aspect-ratio-helper').style.display = "block";
            hideShowButton.className="show";
        }
    }

    hideShowButton.addEventListener('click',toggleContent)
```
 

https://github.com/google/comprehensive-rust/assets/65899331/dd6ef84c-a7b1-407a-a212-ce4776f15546

**Comment by mani-chand** [comment]
If code needs any changes suggest me. If it is completely wrong. suggest me a way if possible.

**Comment by djmitche** [comment]
It looks from the screencast like that's working -- it hides and shows, right?

But, I think it's key that this work without the `aspect-ratio-helper.py` being enabled.

**Comment by mani-chand** [comment]
> It looks from the screencast like that's working -- it hides and shows, right?
> 
> But, I think it's key that this work without the `aspect-ratio-helper.py` being enabled.

What if we add same styles of `aspect-ratio-helper` to some other new div in `theme/book.js` that might work but, If we push the code then it will be a problem for users.

**Comment by djmitche** [comment]
Yes, I think putting it in the .js and/or .css files is the right solution. And it will only be a problem if we push it before it's done :)

**Comment by mani-chand** [comment]
> Yes, I think putting it in the .js and/or .css files is the right solution. And it will only be a problem if we push it before it's done :)

Then, We can keep that part of code as comment and use in dev mode. 
It's the only solution

**Comment by mani-chand** [comment]
If you are ok to comment code and push then , I will make it work.

**Comment by djmitche** [comment]
I'm not sure what you're suggesting. Why would the code be in a comment?

**Comment by mani-chand** [comment]
OH MY BAD English😅 , What I am saying is that, If we write the red box styles in `theme/book.js` it will effect the user but if we comment them than their will be no effect on users.

**Comment by mani-chand** [comment]
We can uncomment them in developing mode.

**Comment by djmitche** [comment]
The reason for this bug is to not have to uncomment anything in order to see the red box, so that wouldn't be a fix to the bug. We need a way to control, in the browser, whether to show or hide the box.

My suggestion is that you break down the project into two parts: first, show the red box all the time; then, set up the way to control whether to show or hide the box.

**Comment by mani-chand** [comment]
> The reason for this bug is to not have to uncomment anything in order to see the red box, so that wouldn't be a fix to the bug. We need a way to control, in the browser, whether to show or hide the box.
> 
> My suggestion is that you break down the project into two parts: first, show the red box all the time; then, set up the way to control whether to show or hide the box.

Sounds bit complex, But, Will keep that in mind and work on it.

**Comment by mani-chand** [comment]
How about adding a button in right side navbar for showing or hiding red box. 
**button will be set to hide red box on default**.

PS ; Not sure that's a good idea what do say. any change or suggestion.

**Comment by mani-chand** [comment]
may be adding a new theme named as dev.

**Comment by djmitche** [comment]
A new theme is an interesting idea -- want to try that out?

**Comment by mani-chand** [comment]
> A new theme is an interesting idea -- want to try that out?
> 

Yes, I will try it out and let you know.

**Comment by mani-chand** [comment]
Hello @djmitche , Check once . Any changes.

https://github.com/google/comprehensive-rust/assets/65899331/73feb008-d7f5-4883-95fc-84021620000a

**Comment by mani-chand** [comment]
> Hello @djmitche , Check once . Any changes.
> 
>  Strings.-.Comprehensive.Rust.-.Google.Chrome.2024-02-22.23-25-58.mp4

Due size of video, I cannot give you a proper demo . everything will be same except that `dev` button in theme.

**Comment by djmitche** [comment]
That looks great!

**Comment by mani-chand** [comment]
Should I go for PR.

**Comment by djmitche** [comment]
Yep!

**Comment by mani-chand** [comment]
Ok.

**Comment by mgeisler** [comment]
Thanks @mani-chand for the work here!

There is one feature I would like to see: I would like us to hide the button with the rectangle when we publish the HTML to https://google.github.io/comprehensive-rust/ — to avoid confusing people who might click it and wonder what the red rectangle is about :smile:

Removing the button will also help give back a little horizontal space. Especially on mobile, this is a very precious resource.

I would suggest updating `.github/workflows/build.sh` with a post-processing step after the call to `mdbook build`. This step should remove the reference to the new JavaScript code. You will probably want to insert a marker in the HTML (a HTML comment) so that you can find the right spot to remove.

The result would be that `mdbook serve` allows you to toggle the rectangle, but when we produce a final build for the website, we avoid showing this developer feature.

**Comment by mani-chand** [comment]
![image](https://github.com/google/comprehensive-rust/assets/65899331/a5bbc95d-c0cd-4e4f-b97e-80c820e16ecb)
Hello @mgeisler , Is this what you mean.

**Comment by mani-chand** [comment]
> ![image](https://private-user-images.githubusercontent.com/65899331/309840945-a5bbc95d-c0cd-4e4f-b97e-80c820e16ecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NzI2NzQsIm5iZiI6MTcwOTU3MjM3NCwicGF0aCI6Ii82NTg5OTMzMS8zMDk4NDA5NDUtYTViYmM5NWQtYzBjZC00ZTRmLWI5N2UtODBjODIwZTE2ZWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE3MTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYmE4MDE2MmRjZTM5MjVhYzNlMTE0MmY4MzJkYTA1NzE5Yjg5OThmOWMzZjM3NzU5M2U4NjVmZjQxOTYzZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O0rGP2mJoXk7yAyeZpoT3CFqx4TRSQrHalo56EKG62g) Hello @mgeisler , Is this what you mean.

It should be before ```if``` if i am not wrong.

**Comment by mani-chand** [comment]
> ![image](https://private-user-images.githubusercontent.com/65899331/309843023-7365e470-a84f-4c02-b3ce-162d263fa15f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NzM2MjIsIm5iZiI6MTcwOTU3MzMyMiwicGF0aCI6Ii82NTg5OTMzMS8zMDk4NDMwMjMtNzM2NWU0NzAtYTg0Zi00YzAyLWIzY2UtMTYyZDI2M2ZhMTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE3Mjg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxNDJiZGRhYTI5ODEyNTBkYzM2NzFkODBiNjNkY2RkMGVhMzgzZWY3OGI4YWQ1YWQ1MzlkZmQ2N2QxZTBlYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.38L3HjOOtKkhg6h1ouE_3vTGSHAMlrsSbmz5za5mLHw) Hello @mgeisler , Is this what you mean.
> 
> It should be before `if` if i am not wrong.

I am not sure why it is not reflecting now running it. , I need some help , What will be the line.

**Comment by djmitche** [comment]
I think `sed` is confusing the `/` delimiting the material to change with the content being replaced. You can use some `.*` to match the path:
```
sed -i '/<!-- MARKER_START -->.*<!-- MARKER_END -->/d'

If that doesn't help, can you push what you've got to the PR?

**Comment by mani-chand** [comment]
@djmitche Once check the PR.
