### ISSUE TITLE
Better course schedule diff

### ISSUE THREAD

**Issue by djmitche** [google/comprehensive-rust#1860]
#1834 fixes the issue of multiple schedule update comments, but the comments themselves are still not very useful.

Let's try to do a smarter diff, that emphasizes the changes the PR makes and not comparison to the target times.

---

# Changes to Course Schedule
This PR changes the course schedule. The new schedule is shown below.

### Fundamentals // Day 2 Morning
_2 hours and 50 minutes_ (5 minutes longer)

* Welcome - _3 minutes_
* Pattern Matching - _1 hour 5 minutes_ (5 minutes longer)
* Methods and Traits - _45 minutes_
* Generics - _40 minutes_

### Fundamentals // Day 3 Morning
_2 hours and 20 minutes_ (10 miutes longer)

* Welcome - _3 minutes_
* Memory Management - _30 minutes_ (30 minutes shorter)
* Ownership -  _40 minutes_ (new segment)
* Smart Pointers - _55 minutes_

**Comment by mgeisler** [comment]
We removed the functionality in #2268 since it wasn't as useful as we had hoped. We can probably close this as well.
