### ISSUE TITLE
Panic during translations rendering

### ISSUE THREAD

**Issue by henrif75** [google/comprehensive-rust#1878]
Building translation step in actions is failing for all .po files
```
Run .github/workflows/build.sh es book/comprehensive-rust-es
  .github/workflows/build.sh es book/comprehensive-rust-es
  shell: /usr/bin/bash -e {0}
  env:
    CARGO_TERM_COLOR: always
    CACHE_ON_FAILURE: false
    CARGO_INCREMENTAL: 0
Building es translation as of [2](https://github.com/google/comprehensive-rust/actions/runs/8162101473/job/22314141282?pr=1869#step:8:2)024-01-25T15:0[3](https://github.com/google/comprehensive-rust/actions/runs/8162101473/job/22314141282?pr=1869#step:8:3):2[4](https://github.com/google/comprehensive-rust/actions/runs/8162101473/job/22314141282?pr=1869#step:8:4)-08:00
  2024-03-0[5](https://github.com/google/comprehensive-rust/actions/runs/8162101473/job/22314141282?pr=1869#step:8:5) 20:3[6](https://github.com/google/comprehensive-rust/actions/runs/8162101473/job/22314141282?pr=1869#step:8:6):42 [INFO] (mdbook::book): Book building has started
  2024-03-05 20:36:44 [INFO] (mdbook::book): Running the exerciser backend
  2024-03-05 20:36:44 [INFO] (mdbook::renderer): Invoking the "exerciser" renderer
  2024-03-05 20:36:45 [INFO] (mdbook::book): Running the html backend
  2024-03-05 20:36:4[8](https://github.com/google/comprehensive-rust/actions/runs/8162101473/job/22314141282?pr=1869#step:8:9) [INFO] (mdbook::book): Running the pandoc backend
  2024-03-05 20:36:48 [INFO] (mdbook::renderer): Invoking the "pandoc" renderer
  Unable to run `pandoc -v`: No such file or directory (os error 2)
  Error: -05 20:36:48 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.
  Error: -05 20:36:48 [ERROR] (mdbook::utils): Error: Rendering failed
  Error: -05 20:36:48 [ERROR] (mdbook::utils): 	Caused By: The "pandoc" renderer failed
  Error: Process completed with exit code [10]
```

**Comment by djmitche** [comment]
I had a similar issue, but assumed it was because I didn't have pandoc (or the right version of it..) installed.

c509dbd9e4eed93fe13f85ae474d52542652c081 should have addressed this, I think? @mgeisler?

**Comment by henrif75** [comment]
Thanks @djmitche 
That might have been a transient error, it's working fine in my last PR (#1879)
I keep this open a little and close later today.

**Comment by henrif75** [comment]
Can't reproduce it anymore.

**Comment by mgeisler** [comment]
> I had a similar issue, but assumed it was because I didn't have pandoc (or the right version of it..) installed.
> 
> [c509dbd](https://github.com/google/comprehensive-rust/commit/c509dbd9e4eed93fe13f85ae474d52542652c081) should have addressed this, I think? @mgeisler?

Hmm... strange — the change in #1713 was not trying to fix this, it was just trying to simplify `build.sh` and also ensure that we always test the PDF generation for all languages for all PRs.

Cc @max-heller in case you have any ideas? The error message above says that `pandoc` wasn't found, so perhaps the `curl` command that installs it simply failed?

**Comment by max-heller** [comment]
> Cc @max-heller in case you have any ideas? The error message above says that `pandoc` wasn't found, so perhaps the `curl` command that installs it simply failed?

Yep, looks to be an issue of `pandoc` not being found in PATH, so either the download failed or adding it to PATH failed
