### ISSUE TITLE
Inform about rustup.sh installation

### ISSUE THREAD

**Issue by taufik-rama** [google/comprehensive-rust#19]
Hello :wave:

Thanks for creating this guide! I've one discussion that I want to make:

At the start, during the setup/installation phase, it seems to currently recommend installing rust's tools using the built-in packages from `apt` repository

https://github.com/google/comprehensive-rust/blob/b411aa688a46c2b90d5eb5aaa0f891e4843a66c6/src/cargo.md?plain=1#L8-L12

I think this might be fine, since this is more familiar with peoples that are just getting started (I know I did this once). Though I think it might be better to also include the ["standard"](https://rustup.rs/) way of installing the tools, since it would make it easier for when latest stable/beta/nightly versions are available (via `$ rustup update`)

```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by mgeisler** [comment]
Hi @taufik-rama, that is a great point! We should include a line linking people to rustup.rs here (I would prefer that over copying the `curl` invocation in case rustup.rs change their mind).

Would you be up for sending s PR with this? Please reference this bug in the PR.

**Comment by taufik-rama** [comment]
Let me know if there's some issue with the copywriting

**Comment by mgeisler** [comment]
> Let me know if there's some issue with the copywriting

Thanks, let me take a look!
