### ISSUE TITLE
Timing information enters the translations

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1982]
Hi @djmitche, I noticed in #1974 that the timing information enters the translations. This is in some sense working as intended, but I fear that it creates extra work for the translators.

On [Welcome to Day 1](https://google.github.io/comprehensive-rust/welcome-day-1.html#welcome-to-day-1), as an example, if we would format

- [Welcome](https://google.github.io/comprehensive-rust/welcome-day-1.html) (5 minutes)
- [Hello, World](https://google.github.io/comprehensive-rust/hello-world.html) (15 minutes)
- [Types and Values](https://google.github.io/comprehensive-rust/types-and-values.html) (40 minutes)
- [Control Flow Basics](https://google.github.io/comprehensive-rust/control-flow-basics.html) (40 minutes)

as a table

| Page | |
| --- | ---:|
| Welcome | 5 minutes |
| Hello, World | 15 minutes |
| Types and Values | 40 minutes |
| Control Flow Basics | 40 minutes |

then the page titles would be extracted on their own — and they would match the title we already extract from each page. So it would reuse the translation for the page, which is kind of neat :slightly_smiling_face: 

I don't have a good idea for how to include the page link like in the current formatting. We include the link in the translatable message, so this would defeat the attempt at unifying the message here with the page title.

**Comment by djmitche** [comment]
The links probably aren't that useful -- they're available in the sidebar as well. We could just omit them.

To be clear, then, the suggestion is to format the schedule as a table rather than a list?
