### ISSUE TITLE
Mistake in Fibonacci Exercise

### ISSUE THREAD

**Issue by withjannis** [google/comprehensive-rust#1985]
The course includes an exercise using the Fibonacci sequence as an example.
In my opinion the implementation is wrong.

The Fibonacci sequence starts with 0, 1, 1. [1]
In the files mentioned, the code implies that the sequence starts with 1, 1, 1.

----

The error is in the following files:

`src/types-and-values/exercise.rs`
`src/types-and-values/exercise.md`

```rust
// src/types-and-values/exercise.rs
fn fib(n: u32) -> u32 {
    if n <= 2 {
        return 1;
    } else {
        return fib(n - 1) + fib(n - 2);
    }
}
```

Using this algorithm, this would be the output:
```rust
fib(0); // output: 1, IS WRONG
fib(1); // output: 1
fib(1); // output: 1
```
----

This fix would correct the implementation of the code.

```rust
fn fib(n: u32) -> u32 {
    if n < 2 {
        return n;
    } else {
        return fib(n - 1) + fib(n - 2);
    }
}
```

[1] https://en.wikipedia.org/wiki/Fibonacci_sequence

_Disclaimer: This is my first issue, I would appreciate feedback._

**Comment by mgeisler** [comment]
Thanks @withjannis for fixing this! Could I get you to add a reference to https://oeis.org/A000045 in a comment? That should help keep this stable going forward since that sequence is well-defined.

**Comment by withjannis** [comment]
I can't quite follow you @mgeisler, sorry.
Where would you like to add a comment referring to https://oeis.org/A000045, in `src/types-and-values/exercise.rs`?

**Comment by mgeisler** [comment]
Yes, exactly! Please add it as a speaker note for future reference for people who view/edit the page.

**Comment by mgeisler** [comment]
I think we can close this bug now since the sequence is fixed — a speaker note can be added later, if people think it would be helpful.
