### ISSUE TITLE
Inconsistent text in CR2

### ISSUE THREAD

**Issue by Enes1313** [google/comprehensive-rust#1993]
"Hard-code both functions to operate on 3 × 3 matrices." in **tuples-and-arrays/exercise.md** text should change. In the relevant file before CR2, the implementation of two functions was requested.

**Comment by djmitche** [comment]
I'm not sure what you're suggesting. Can you make a PR to be precise?

**Comment by Enes1313** [comment]
I don't know if I will make any changes other than the relevant file. That's why I just opened an issue. I think the "both" and "s" ending will be deleted. If there will be changes only in the relevant file, I can open PR :)

**Comment by djmitche** [comment]
Ah, OK - that sentence is a little out of order.
