### ISSUE TITLE
Question about "Speaker Notes" in Destructuring page

### ISSUE THREAD

**Issue by sahuang** [google/comprehensive-rust#2023]
The "Speaker Notes" in [Destructuring](https://google.github.io/comprehensive-rust/pattern-matching/destructuring.html) Enums mentioned that:

> Save the result of `divide_in_two` in the `result` variable and `match` it in a loop. That won’t compile because `msg` is consumed when matched. To fix it, match `&result` instead of `result`. That will make `msg` a reference so it won’t be consumed.

However, I tried this and it compiles successfully even without the `&`. Is it because new `rustc` version somehow fixed this issue? 

![image](https://github.com/google/comprehensive-rust/assets/26035292/b815c907-fb3c-4845-8bde-ce563dbec74d)

**Comment by djmitche** [comment]
I think the missing bit is "in a loop"

```
fn main() {
    let n = 100;
    let result = divide_in_two(n);
    loop {
        match result {
            Result::Ok(half) => println!("{n} divided in two is {half}"),
            Result::Err(msg) => println!("sorry, an error happened: {msg}"),
        }
    }
}
```

BTW, please try to use text to represent text, rather than images -- in this case I couldn't copy/paste from your example because it's an image.

**Comment by sahuang** [comment]
Thanks! Noted.
