### ISSUE TITLE
Page `Exercise: Iterator Method Chaining` rust code not rendering

### ISSUE THREAD

**Issue by peter-lockhart-pub** [google/comprehensive-rust#2104]
When viewing this page in Chrome, I do not see the coding exercise https://google.github.io/comprehensive-rust/iterators/exercise.html

![Screenshot 2024-05-29 at 10 01 57](https://github.com/google/comprehensive-rust/assets/60918964/bfa8421d-087e-40eb-848a-07a3f162c191)

OSX
Chrome Version 125.0.6422.78 (Official Build) (x86_64)

**Comment by djmitche** [comment]
Hm, I see it "flash" into existence and then disappear. I wonder if this has to do with the code-saving functionality?

**Comment by fw-immunant** [comment]
I believe this is fixed now.
