### ISSUE TITLE
Most code snippets don't work anymore

### ISSUE THREAD

**Issue by CCristi** [google/comprehensive-rust#2105]
As the title says, most code snippets don't work anymore

https://google.github.io/comprehensive-rust/concurrency/sync-exercises/solutions.html 
https://google.github.io/comprehensive-rust/iterators/exercise.html
https://google.github.io/comprehensive-rust/modules/exercise.html
etc...

**Comment by mgeisler** [comment]
Thanks for reporting this, @CCristi! We've reverted the broken change and will have to test this better next time!

**Comment by CCristi** [comment]
Thanks, it is working now 🙌 
Great rust course, btw!!!
