### ISSUE TITLE
Dead link found in the glossary.md translations

### ISSUE THREAD

**Issue by HuyNVuong** [google/comprehensive-rust#2110]
See attached image here 
![image](https://github.com/google/comprehensive-rust/assets/35347897/537b0ef9-36d6-4410-b003-dfc8a621bcea)

I think the current link obsolete and should be replaced. Please take a loook

**Comment by djmitche** [comment]
Side-point: in general in a mostly-textual medium such as a github issue, it's better to include text rather than an image of that text, as it allows copy/paste and is easier to search for.
