### ISSUE TITLE
The language switching menu requires clicking on the text, not elsewhere in the menu item

### ISSUE THREAD

**Issue by zhuba-Ahhh** [google/comprehensive-rust#2132]
The language switching button seems to need to be clicked twice to take effect

**Comment by djmitche** [comment]
Could you say more? I just tried:

 * click the globe icon
 * click on a language

result:

 * page switched to that language

**Comment by djmitche** [comment]
Oh, I did notice that if I click on the row in the menu, but not on the actual text, it does nothing. For example, clicking to the right of the word "English".

Is that what you're seeing?

**Comment by zhuba-Ahhh** [comment]
> Oh, I did notice that if I click on the row in the menu, but not on the actual text, it does nothing. For example, clicking to the right of the word "English".
> 
> Is that what you're seeing?

Sorry, it seems my network is stuck.

**Comment by zhuba-Ahhh** [comment]
I seem to have discovered that clicking on the blank part of the picture below will not work. You can try to reproduce it.
you Can confirm whether this needs adjustment
<img width="361" alt="image" src="https://github.com/google/comprehensive-rust/assets/84793349/00a373f5-f600-42b8-8d76-82a3a4070827">

**Comment by djmitche** [comment]
Agreed, there is a bug in the target area there!
