### ISSUE TITLE
dprint fmt failing

### ISSUE THREAD

**Issue by djmitche** [google/comprehensive-rust#2165]
```
Run dprint/check@v2.2
Run curl -fsSL https://dprint.dev/install.sh | sh -s  > /dev/null 2>&1
Run ~/.dprint/bin/dprint check
Compiling https://plugins.dprint.dev/json-0.17.4.wasm
Compiling https://plugins.dprint.dev/toml-0.[5](https://github.com/google/comprehensive-rust/actions/runs/9638343597/job/26600420163#step:5:6).4.wasm
Compiling https://plugins.dprint.dev/markdown-0.16.2.wasm
from /home/runner/work/comprehensive-rust/comprehensive-rust/src/user-defined-types/static.md:
 8  8| therefore·will·not·move:
 9  9| 
10 10| ```rust,editable
11 11|+rewriting·static
12 11| static·BANNER:·&str·=·"Welcome·to·RustOS·3.14";
13 12| 
14 13| fn·main()·{
--
```
etc.

This looks like a debug print, but I don't see that in any of the `dprint` repos. It doesn't reproduce locally. If I remove `~/.cache/dprint`, I get _other_ errors, in formatting of the `.po` files, but not these errors (I'll make a PR for that).

`dprint.json` suggests it's running nightly `rustfmt` for Rust stuff, so perhaps that's responsible? Indeed, https://github.com/rust-lang/rustfmt/issues/6213.

**Comment by mgeisler** [comment]
@kdarkhan actually ran into this recently in mdbook-i18n-helpers: https://github.com/google/mdbook-i18n-helpers/pull/205#discussion_r1651724307. We should have made more noise about it so you would have seen it here.
