### ISSUE TITLE
Link check runs on all languages

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#2247]
After merging #2195, I realized that `mdbook-linkcheck` runs on all languages. This is despite our best efforts in `build.yml` where we only install the tool on known-good languages:

https://github.com/google/comprehensive-rust/blob/ad9b41cd6cba0b87a2560a155fc5afff1f41713d/.github/workflows/build.yml#L150-L153

The problem is likely due to caching: while we only store the cache when building the English version, we use the cache for all languages.

**Comment by mgeisler** [comment]
@jond01, would you be able to take a look at this?

I think we could clear the `mdbook-linkcheck` configuration in the `book.toml` file when we detect that we don't want to run the tool. We could perhaps also just delete the tool preemptively if we see it — since we only store the cache for English, this should work okay.

**Comment by jond01** [comment]
Hi, sure. It's strange that it happened only now, I will check the caching issue as you suggest.
Attaching a failed run for reference:
https://github.com/google/comprehensive-rust/actions/runs/10055807495/job/27793284713
