### ISSUE TITLE
Casting chapter's one sentence understanding

### ISSUE THREAD

**Issue by ahan** [google/comprehensive-rust#2284]
In [17.4. Casting](https://google.github.io/comprehensive-rust/std-traits/casting.html) chapter, there is one sentence is not quite clear to me, which is `TryFrom and TryInto are available when you want to handle casts that fit differently from those that don't`.

I confused `that don't` these two words, I'm a little lost here, `don't` what or `don't` which.

I try to seek it from [translation version](https://google.github.io/comprehensive-rust/zh-CN/std-traits/casting.html), but no luck.

😂 Can you help describe it deeper for me? Thanks a lot.

**Comment by fw-immunant** [comment]
"`TryFrom` and `TryInto` are available when you want to handle casts that fit differently from casts that don't [fit]."

**Comment by ahan** [comment]
@fw-immunant thanks
