### ISSUE TITLE
Async dining philosophers does not avoid deadlock the way the sync exercise does

### ISSUE THREAD

**Issue by djmitche** [google/comprehensive-rust#2371]
### Discussed in https://github.com/google/comprehensive-rust/discussions/2367

<div type='discussions-op-text'>

<sup>Originally posted by **xiaohu-zhang** September 15, 2024</sup>
Dining Philosophers execise solution in 67.3 is Livelock.Why not use the same idea of 62.3?</div>

**Comment by djmitche** [comment]
Dupe of #2368.

**Comment by xiaohu-zhang** [comment]
no problem.I will pull a pr to fix it.
