### ISSUE TITLE
JavaScript tests

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#2462]
Today, we don't have any tests for the JavaScript code found in

- https://github.com/google/comprehensive-rust/blob/main/theme/book.js: executes the Rust Playground code (comes from the upstream `mdbook` project).
- https://github.com/google/comprehensive-rust/blob/main/theme/speaker-notes.js: our own home-grown speaker note system.
- https://github.com/google/comprehensive-rust/blob/main/theme/save-playgrounds.js: not used currently, could save the state of a playground between page loads.

This has caused bugs in the past (the playgrounds disappeared at some point) and it makes it hard to upgrade `mdbook` (because we need to  merge in changes to `book.js` manually).

It would be very helpful to have tests for these files. This should be something we can run on the command line in GitHub CI. I think we need something which 

- We can run on pre-rendered HTML files. I envision us running `mdbook build` (for each language).
- A headless browser would then be needed to inspect the pages.
- We would need a unit testing framework of some sort.
  - I used https://www.protractortest.org/ in the past, but there are many others.

**Comment by michael-kerscher** [comment]
I created a first demo in that pull request to open a discussion before investing more in that direction.
