### ISSUE TITLE
Clarify Protobuf exercise (lifetimes)

### ISSUE THREAD

**Issue by mering** [google/comprehensive-rust#2466]
Without knowing the Protobuf wire format, the exercise description and example code is hard to understand.
It would have helped to add an additional sentence describing that submessages (like `PhoneNumber` as part of `Person`) are encoded as `Len` type of the encoded submessage (1. encode `PhoneNumber` 2. store it as `Len` type field in the `Person` wire format).

Also the name `Len` for basically a length annotated byte array is a bit unintuitive.

Furthermore, it would have helped to have the tests already be presented as part of the exercise and not only as part of the solution.

**Comment by djmitche** [comment]
Thanks! I'll add some more explanation of the protocol format. You're right that LEN isn't very intuitive, but it's how Proto is defined!

I'll move the tests into `main` to make them visible.
