### ISSUE TITLE
Improve Luhn algorithm (testing)

### ISSUE THREAD

**Issue by mering** [google/comprehensive-rust#2467]
The solution of the Luhn algorithm could be improved to include the following within the loop in order to avoid overflows:
```rust
sum = sum % 10;
```

When using an `u8` for `sum`, this can be tested with the following assertion:
```rust
assert!(luhn("99999 99999 99999 99999 99999 9998"));
```

**Comment by djmitche** [comment]
I'm not sure what you mean by "using an `u8` for `sum`" -- that's a u32, and `char::to_digit` returns a u32, so using a `u8` for the sum is not an easy bug to write.

You're right that, if we were using this for other than credit card validation, in a production context, that would be a good fix. But, the exercise is to find and fix bugs -- so I think we should leave this potential overflow in and call this is an "extra credit" answer!

**Comment by mering** [comment]
Using an u8 already in the exercise code is not only more efficient but also makes the overflow easier to reproduce. Especially since the fix is easy.
Not handling overflows is a major gap IMHO.

**Comment by djmitche** [comment]
Sorry, I don't see `u8` in the exercise already, although I agree it would make the overflow easier to reproduce.

I'm going to close this, as the exercise already describes the given code as "buggy". You've identified an additional bug which particularly sharp students might also find and fix.
