### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#284]
For reference: https://github.com/thecodix/book and https://github.com/ManRR/rust-book-es.

**Comment by mgeisler** [comment]
Here is a Google Translate version to get you started: [es.zip](https://github.com/google/comprehensive-rust/files/10555902/es.zip)

**Comment by wfranck** [comment]
could I help with this issue? I had not seen that the ticket for Spanish was open and I made progress with the translation.

**Comment by mgeisler** [comment]
Hi @wfranck, yes please! I haven't heard of any progress being made here, so I suggest you add a link to your repository/branch here. Then perhaps @antodellanzo can end up helping you :smile:

**Comment by wfranck** [comment]
Thank you.  At the moment I only have it local and installed the project to see the changes following the instructions of the project. I'll upload changes later.

**Comment by wfranck** [comment]
I forked the project and started with the first commit translated until prior to the start of the 'Days' of the course
https://github.com/wfranck/comprehensive-rust/blob/main/po/es.po

**Comment by wfranck** [comment]
I will continue reading the course in English without doing the translation or, working and have this in my own repository. I'm sure someone will be able to translate it better.

**Comment by mgeisler** [comment]
> I will continue reading the course in English without doing the translation or, working and have this in my own repository. I'm sure someone will be able to translate it better.

Okay, thanks for the work you did! I will talk to the people who can read Spanish and try to merge in the parts you already translated. Then I hope more people from the community will jump in and help.

**Comment by mgeisler** [comment]
@henrif75, when you get the translation back from the Localization team, you will need to normalize it using `mdbook-i18n-normalize`. After that, I suggest splitting it into a PR per top-level directory (using `msggrep`).

@antodellanzo, I'll remove you as the assignee here, but feel free to send us PRs if you find the time!

**Comment by mgeisler** [comment]
Hi all, I just learnt about https://rustlanges.github.io/ from https://github.com/rust-lang/book/issues/661#issuecomment-1730766276. Perhaps it could be useful for people here.

**Comment by mgeisler** [comment]
It would be great if we could reach out to them and see if there is a way to collaborate!

**Comment by mgeisler** [comment]
Hi all! I wanted to let you know about #1460. This is an update to mdbook-i18n-helpers which will remove ~6k lines from your PO file. It changes the way code blocks are processed: we now extract strings and comments directly.

You need to run `mdbook-i18n-normalize` on your PO file to preserve the translations found here: https://google.github.io/comprehensive-rust/es/hello-world/small-example.html (and any other places where you have translated comments).

You can do this before/after refreshing the translation. See #1461 for an example PR which shows the state after normalization.

**Comment by SergioRibera** [comment]
Hello @mgeisler, I come from the @RustLangES community.

We would like to express our interest in contributing more actively to translation and related tasks in comprehensive-rust. We believe that by adopting a more hands-on approach in our native language, we can further improve the quality and efficiency of the project.

We are open to further discussion on this topic and would welcome your guidance on how best to move forward for the continued success of the project.

For now I leave the profiles of the most active members of the community in translation issues (@CrawKatt @Phosphorus-M @Lemin-n and me)

Thank you for considering our collaboration.

**Comment by henrif75** [comment]
Hi @SergioRibera, thanks so much for reaching out! I'm helping @mgeisler with the community translation community.
Any contribution is very much welcome!
Everything one needs to do to help with translations is at [(TRANSLATIONS.MD).](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md).
I'll reopen this issue as you might want to reach out to the Spanish-speakers willing to contribute.
Please let me know if you have any other questions!

**Comment by henrif75** [comment]
The untranslated content from v2 was sent to the translation service.

**Comment by henrif75** [comment]
Closing this issue since we're done with the core translation work.
