### ISSUE TITLE
Can it be made a PWA?

### ISSUE THREAD

**Issue by codad5** [google/comprehensive-rust#322]
I think it would be cool if it can be made a progressive web app installable on your device, so it could increase performance and not rely on the network for some time, especially when the internet network tends to fail at some particular region

**Comment by mgeisler** [comment]
Hi @codad5,

Yes, that would be very cool indeed! Right now, your best bet is probably to use the "printed" version of the course: https://google.github.io/comprehensive-rust/print.html

That gives you everything on a single page. You could also build the course yourself using `mdbook build` and then put the resulting HTML pages onto any webserver you like.

If you're talking about the interactive playground examples, then they're being run on https://play.rust-lang.org/ right now. I don't know if anybody has experimented with turning the whole compiler into a Wasm project and running it in the browser... :smile:

**Comment by mgeisler** [comment]
I think the issue belongs in https://github.com/rust-lang/mdbook instead since that's the tool we use to generate the HTML. I'll close the issue to reflect that won't work on this anytime soon.
