### ISSUE TITLE
Bumping version numbers in cargo/running-locally.md?

### ISSUE THREAD

**Issue by gendx** [google/comprehensive-rust#333]
This page mentions:

> At the time of writing, the latest stable Rust release has these version numbers:
> 
> ```
> % rustc --version
> rustc 1.61.0 (fe5b13d68 2022-05-18)
> % cargo --version
> cargo 1.61.0 (a028ae4 2022-04-29)
> ```

Should these numbers be bumped once in a while (together with making sure that the code snippets are still up-to-date with the latest standards - e.g. Clippy lints)?

It could also be mentioned that all the code snippets are using stable Rust, and therefore are expected to still compile in years (so readers shouldn't worry if the rustc version looks old).

**Comment by mgeisler** [comment]
> Should these numbers be bumped once in a while (together with making sure that the code snippets are still up-to-date with the latest standards - e.g. Clippy lints)?

Good question... since we use stable Rust (as you mention), I think it's fine to not bump the version numbers here more than 1-2 times a year.

> It could also be mentioned that all the code snippets are using stable Rust, and therefore are expected to still compile in years (so readers shouldn't worry if the rustc version looks old).

That's a great point and something I hadn't thought about. A line about that would be great.
