### ISSUE TITLE
Make the shell snippets easier to copy/paste (e.g. cargo/running-locally.md)?

### ISSUE THREAD

**Issue by gendx** [google/comprehensive-rust#334]
The code blocks of `mdbook` provide a "Copy to clipboard" button - however pages like https://google.github.io/comprehensive-rust/cargo/running-locally.html contain shell blocks like follows:

```
$ cargo new exercise
     Created binary (application) `exercise` package
```

Clicking copies the whole block, including the dollar sign and the shell output. It would be nice to be able to only copy the command, e.g. `cargo new exercise`. We could achieve that by:
1. Creating a separate block for the output.
2. Removing the dollar sign. This would however make it less obvious that it's a shell command. Unless `mdbook` provides a way to display a dollar sign before the content, but exclude it from the copying?

WDYT?

**Comment by mgeisler** [comment]
Yeah, that's definitely an annoyance. It's reported upstream here: https://github.com/rust-lang/mdBook/issues/864.

People tried to fix it repeatedly: https://github.com/google/comprehensive-rust/pull/25 and https://github.com/google/comprehensive-rust/pull/29. So we should probably do something about it...

My idea would be to fix it upstream, but I haven't taken the time to do that.

**Comment by gendx** [comment]
Glad to see it's already reported upstream :)

**Comment by mgeisler** [comment]
Our style guide actually talks about this: https://developers.google.com/style/code-syntax#prompt.

The system used there knows to not copy the `$`, even for examples that contain multiple commands. I think we should enhance `mdbook` with a similar capability.

**Comment by mgeisler** [comment]
Fixed via #951.

**Comment by mgeisler** [comment]
If `mdbook` ever gets support for not copying the prompt, then we can consider adding the prompts back. For now, it's probably better to remove them since this has been suggested repeatedly :smile:

**Comment by sharunkumar** [comment]
Oh alright I could check it out

**Comment by sharunkumar** [comment]
> We could separate the output from the shell commands (like you did in your PRs)

@mgeisler when doing [this](https://github.com/google/comprehensive-rust/pull/955/commits/17d8358be26c6ae2c6ed04456aa66c51bef191e9), the test build [fails](https://github.com/google/comprehensive-rust/actions/runs/5525362750/jobs/10078892609?pr=955#step:11:175) on the PR

I noticed this when I tried it in the previous PR itself, not sure how to fix it

**Comment by mgeisler** [comment]
> > We could separate the output from the shell commands (like you did in your PRs)
> 
> @mgeisler when doing [this](https://github.com/google/comprehensive-rust/pull/955/commits/17d8358be26c6ae2c6ed04456aa66c51bef191e9), the test build [fails](https://github.com/google/comprehensive-rust/actions/runs/5525362750/jobs/10078892609?pr=955#step:11:175) on the PR
> 
> I noticed this when I tried it in the previous PR itself, ~not sure how to fix it~
> 
> Update: figured it out, had to specify the language for the new code block

Great that you figured it out — the error looks very mysterious at first! :smile:
