### ISSUE TITLE
Remove `prefer_rlib: true` from `Android.bp` files

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#371]
The line makes Soong statically compile all Rust dependencies. This in turn makes it easy to copy examples to the emulator. However, this mode is not the default and it can cause problems with doubly-defined symbols.

**Comment by spoloxs** [comment]
I removed `prefer_rlib: true` from `Android.bp` files and raised the PR please check and tell if something is wrong or missing.

**Comment by mgeisler** [comment]
Done via #895.
