### ISSUE TITLE
Default embedded playground is often timing out, slowing down the course.

### ISSUE THREAD

**Issue by gendx** [google/comprehensive-rust#406]
While running the course, the playground was often timing out, especially when editing and re-running a snippet multiple times in a row (rate limiting?).

Maybe we could find a way to:
- Increase the timeout? A slower timeout attempted only once is better than retrying 5 times until it succeeds.
- Spawn a local playground and connect mdbook to that?

The course is quite dense, and these small interruptions to wait for the playground were not a good use of time.

**Comment by mgeisler** [comment]
> * Increase the timeout? A slower timeout attempted only once is better than retrying 5 times until it succeeds.

We can do that by copying https://github.com/rust-lang/mdBook/blob/master/src/theme/book.js into our `theme/` folder. We'll then modify the 6 second timeout found there.

> * Spawn a local playground and connect mdbook to that?

I have already set that up locally — but it's not yet running continuously. Investing time in that would be a great improvement. We could start by documenting the steps somewhere here :smile:
