### ISSUE TITLE
Translation error in Brazilian translation for pattern-matching.html

### ISSUE THREAD

**Issue by gendx** [google/comprehensive-rust#415]
See:
- English page: https://google.github.io/comprehensive-rust/pattern-matching.html
- Brazilian page: https://google.github.io/comprehensive-rust/pt-BR/pattern-matching.html.

It looks like the pattern for the character `a` got translated into two letters `um` in the code, which breaks compilation.

Maybe the GitHub Actions checking the translations should also run `mdbook test` on the translated contents to check that the code snippets still compile?

---

![image](https://user-images.githubusercontent.com/4346404/219077042-fc444820-fa94-4d6f-ad8b-bf81de2d272f.png)

**Comment by mgeisler** [comment]
> Maybe the GitHub Actions checking the translations should also run `mdbook test` on the translated contents to check that the code snippets still compile?

Yes, we actually do exactly that — but it doesn't work as intended until https://github.com/rust-lang/mdBook/pull/1986 is merged.

**Comment by mgeisler** [comment]
This was fixed by #416 and will be long-term fixed by rust-lang/mdBook#1986.
