### ISSUE TITLE
Make `i18n-helpers` a requirement for running `mdbook`

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#434]
We can simplify the setup a bit by making the `i18n-helpers` a mandatory requirement for running `mdbook`.

I was originally hesitant to complicate the setup instructions, but since people already have to install `mdbook-svgbob`, I now think it will be fine to also ask them to install `i18n-helpers`.

We should also think about publishing `i18n-helpers` to crates.io so that people can install it easily for other projects. That's more of a long-term plan, though.

**Comment by mgeisler** [comment]
Doing this would remove some warnings triggered by #429 and #421.

**Comment by jooyunghan** [comment]
Fixed with #461 

Publishing it could be another story.
