### ISSUE TITLE
Methods used in exercise before they are introduced

### ISSUE THREAD

**Issue by djmitche** [google/comprehensive-rust#510]
Day one's afternoon exercises use methods, but these aren't described until day 2.  The afternoon exercises use traits as well (Iterator, IntoIterator), but perhaps those are more easily explained away with references to future slides.

**Comment by mgeisler** [comment]
Yeah, methods are only mentioned [very briefly on Day 1](https://google.github.io/comprehensive-rust/basic-syntax/methods.html) and I don't think traits are mentioned at all. This is something we need to fix.

I'm slowly starting to work on a restructuring of the course following feedback from you, @CasperN (in #156), and others internally at Google. Avoiding these "forward references" is high on the wish list :smile:  They add a lot of extra work for the instructor who now have to be aware of this and casually explain things like methods early.

**Comment by mgeisler** [comment]
This will be fixed with #913!
