### ISSUE TITLE
Day 1 Afternoon Exercises Solution Incomplete

### ISSUE THREAD

**Issue by bngoalie** [google/comprehensive-rust#520]
For "Designing a Library", the main still has commented-out code.

For "Iterators and Ownership", there is no discussion on the questions proposed in the exercise.

**Comment by inglorion** [comment]
I think the description needs to be updated.

"Iterators and Ownership" is now in Day 2, Morning.

I don't see "Designing a Library" in the exercises. Is this in "Storing Books" (Day 2) now?

With the updated description, I can take a look. Assigning to mgeisler for confirmation.

**Comment by mgeisler** [comment]
Hi @inglorion! Thanks for the interest! Yes, you're spot on: we recently moved things around in #913.

- [`day-1/solutions-morning.html`](https://google.github.io/comprehensive-rust/exercises/day-1/solutions-morning.html) does not provide a solution for [`day-1/implicit-conversions.html`](https://google.github.io/comprehensive-rust/exercises/day-1/implicit-conversions.html).
- [`day-2/solutions-morning.html`](https://google.github.io/comprehensive-rust/exercises/day-2/solutions-morning.html) says "Designing a Library" but [`day-2/book-library.html`](https://google.github.io/comprehensive-rust/exercises/day-2/book-library.html) says "Storing Books".
- [`day-2/iterators-and-ownership.html`](https://google.github.io/comprehensive-rust/exercises/day-2/iterators-and-ownership.html) has no solution.

I think that's all from a quick look at the pages, but there might very well be more small problems here — a good starting point would actually be #319, which is just about making the solutions easier to read.

**Comment by fw-immunant** [comment]
I don't think these problems exist anymore.
