### ISSUE TITLE
Show `stderr` from code blocks

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#531]
Today, mdbook doesn't show `stderr` when running Rust code. The problem is that it uses a Playground endpoint which doesn't deliver this information. However, the Playground itself does have this information via an internal endpoint. See https://github.com/rust-lang/mdBook/pull/1315 for details.

Fixing this would allow us to start using `dbg!(foo)` instead of `println!("foo: {foo:?}")` in our code samples and thus simplify a lot of code blocks.

With https://github.com/google/mdbook-i18n-helpers/pull/75 merged, many more code blocks would be automatically removed from the translation files, thus reducing churn for our translators.

**Comment by osiris5498** [comment]
I'll try to work on it in the next two weeks.

**Comment by mgeisler** [comment]
Thanks Emma! You might very likely have to make changes to the upstream `mdbook` — we should upstream as much as possible, both so it can benefit everybody and so we can avoid carrying patches (which makes it hard to update our version of `mdbook`).

**Comment by Alx-Lai** [comment]
Hi @mgeisler, I applied rust-lang/mdBook#1315 in #2397. I think there's a room to discuss whether we should push it to upstream repo. My concern is that the original PR is put aside for a long time so we don't know if i'll be finally adopted or not; however, if we merge it first in downstream, the only possible effort comes iff it's finally adopted in upstream.

**Comment by mgeisler** [comment]
With #2397 merged, we can finally start using `dbg!` throughout the course! I suggest we close this as finished now and then create a new issue to focus on this conversion.

**Comment by mgeisler** [comment]
I created #2478 to track converting print statements to `dbg!`.

**Comment by mgeisler** [comment]
The change in #2397 did somehow not work when deployed — I don't know why, but I saw 500 Server Errors on every request. I reverted the change for now, but I hope we can fix it soon.

**Comment by mgeisler** [comment]
This was added again #2503, so this is now fixed! Thanks a lot, @Alx-Lai!
