### ISSUE TITLE
Rust trademark

### ISSUE THREAD

**Issue by jasiukiewicztymon** [google/comprehensive-rust#574]
I'm not sure if you're able to use the website style, or service name, after the new Rust trademark update...

**Comment by mgeisler** [comment]
> I'm not sure if you're able to use the website style, or service name, after the new Rust trademark update...

Hi @jasiukiewicztymon, yeah, I saw the discussion around the proposed trademark policy. We'll update things as needed if/when a final policy is published :slightly_smiling_face:

**Comment by mgeisler** [comment]
Right now, I don't think there is anything for us to do here — let's create a new issue if/when there is something for us to change.
