### ISSUE TITLE
[ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md in "/home/user1/cargo/src" directory

### ISSUE THREAD

**Issue by llagerlof** [google/comprehensive-rust#62]
I created an empty directory called cargo in my home directory. Inside it I successfully ran:

```
$ cargo install mdbook
$ cargo install mdbook-svgbob
```

And then tried to run:

```
$ mdbook test
$ mdbook serve
```

But both commands above (test and serve) gives me the same error:

```
2022-12-26 13:34:39 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md in "/home/user1/cargo/src" directory
2022-12-26 13:34:39 [ERROR] (mdbook::utils): 	Caused By: No such file or directory (os error 2)
```

**Comment by maurer** [comment]
It sounds like nowhere in this process did you check out `comprehensive-rust`. You must either pass the path to the checked out repository as an argument or run these commands from inside the checked out repository.

Please see the [`mdbook` documentation](https://rust-lang.github.io/mdBook/cli/serve.html#specify-a-directory) for further information.

**Comment by llagerlof** [comment]
I had the book checked out, but not passed the path as argument to `mdbook serve`. Thank you.
