### ISSUE TITLE
Technical nits: Slices and other DSTs

### ISSUE THREAD

**Issue by QuineDot** [google/comprehensive-rust#64]
I don't think you ever cover what a non-`Sized` type, aka dynamically sized type (DST), is.

- [x] [Here](https://google.github.io/comprehensive-rust/basic-syntax/scalar-types.html) you call `&str` and `&[u8]` "scalar types", and... while the *reference* is, I suppose... the underlying (DST) slice contains multiple values, so I found their inclusion surprising.

- [x] [Then later on](https://google.github.io/comprehensive-rust/basic-syntax/slices.html) you refer to `&[T]` as a slice.  This is common nomenclature, but I feel it's worth pointing out that a `[T]` is more properly the slice, it is dynamically sized, and this is why you typically see it behind a reference (or other pointer like in a `Box`).  And [then on this page](https://google.github.io/comprehensive-rust/basic-syntax/string-slices.html) you could say a `str` is basically a `[u8]` with invariants (valid UTF8 encoding).  

Incidentally, that page says there are two Rust string types, but there are many others, such as `Arc<str>` or `Cow<'_, str>`.

---

- [ ] [Then later on](https://google.github.io/comprehensive-rust/std/box-recursive.html) you say
> Recursive data types or data types with dynamic sizes need to use a Box

But that's incorrect:
* There are no dynamic sizes here in Rust terminology; `List<T>` has a static size
* If you attempt to write `List` without the `Box`, it has *infinite* size -- but still not dynamic
* Slices have dynamic sizes but don't need a `Box`

---

- [x] [When you get around to trait objects,](https://google.github.io/comprehensive-rust/generics/trait-objects.html) you can mention that they're DSTs too, and that's why you typically see them in a `Box` (but may also seem them behind a reference, in an `Arc`, ...).

**Comment by fw-immunant** [comment]
- `&str` and `&[u8]` are no longer described as scalar types.
- `&[T]` is more commonly known as a slice than the DST, just because DST usage is uncommon in general. I think it's best to avoid talking about DSTs early on as it requires invoking several concepts at once to be able to work with them.
- Filed PR #2283.
- We now mention the required pointer indirection for trait objects [here](https://google.github.io/comprehensive-rust/generics/dyn-trait.html).
