### ISSUE TITLE
Technical nits: the try operator

### ISSUE THREAD

**Issue by QuineDot** [google/comprehensive-rust#65]
[You only cover `Result`,](https://google.github.io/comprehensive-rust/error-handling/try-operator.html) but [it works with other types too.](https://doc.rust-lang.org/std/ops/trait.Try.html#implementors)  At least mention `Option`, which is commonly used.

[The desugaring example](https://google.github.io/comprehensive-rust/error-handling/converting-error-types.html) is out of date; [the actual desugaring](https://rust-lang.github.io/rfcs/3058-try-trait-v2.html#desugaring-) is now more complicated.  (And technically it was never just `From::from` directly.)  But I get it, you're not going to help anyone by explaining it on that level.  Probably you can just rephrase this page to "the effective expansion ..." instead of "actual expansion", and "works the same as" instead of "actually becomes".

Consider adding the as-if desugaring for `Option` too.

**Comment by mgeisler** [comment]
> Probably you can just rephrase this page to "the effective expansion ..." instead of "actual expansion", and "works the same as" instead of "actually becomes".

Great idea, thanks!


> [You only cover `Result`,](https://google.github.io/comprehensive-rust/error-handling/try-operator.html) but [it works with other types too.](https://doc.rust-lang.org/std/ops/trait.Try.html#implementors) At least mention `Option`, which is commonly used.

True! I will add this to the speaker notes, or perhaps we can squeeze it into the slide somewhere.
