### ISSUE TITLE
Suggestion: Don't shy away from concurrent structures early on

### ISSUE THREAD

**Issue by QuineDot** [google/comprehensive-rust#67]
I found it sort of odd that `Arc` and friends weren't mentioned until the last day, while for example you have [a slide on `Rc` (also mentioning `RefCell` and `Cell` in passing)](https://google.github.io/comprehensive-rust/std/rc.html)  Why not mention `Arc` as well?  If you use `Rc`, you're opting out of being able to be multi-threaded... and one of the great things about Rust is how it assumes you're going to want to be concurrent eventually.  If `Rc<T>` meets your shared-ownership needs, usually `Arc<T>` does too.

Other places they come up:
* [`Arc<str>` (or `Rc`) as a string type](https://github.com/google/comprehensive-rust/issues/64)
* [`Arc<Self>` (or `Rc`) as a method receiver](https://google.github.io/comprehensive-rust/methods/receiver.html)
* [Global state](https://github.com/google/comprehensive-rust/issues/66)

**Comment by mgeisler** [comment]
Good point. Let me start by mentioning `Arc` on the `Rc` page (#83).
