### ISSUE TITLE
zh-CN: translate src/basic-syntax/variables.md, src/basic-syntax/type-inference.md and some words in SUMMARY.md

### ISSUE THREAD

**Issue by Eventide** [google/comprehensive-rust#796]
Part of https://github.com/google/comprehensive-rust/issues/324

**Comment by mgeisler** [comment]
Hi @Eventide and @anlunx, I think this can be closed?

I noticed that #797 was closed instead of merged — did you submit the changes some other way? :slightly_smiling_face:

**Comment by Eventide** [comment]
Hi @mgeisler ,
I think I may need to re-create the PR. I will do it later today.

Thanks for the reminder.

**Comment by mgeisler** [comment]
> Hi @mgeisler , I think I may need to re-create the PR. I will do it later today.
> 
> Thanks for the reminder.

No problem, happy to help where I can! :smile:
