### ISSUE TITLE
Disclose `.po` fmt options

### ISSUE THREAD

**Issue by Throvn** [google/comprehensive-rust#827]
Whenever I edit a file with PoEdit, I get a tremendously large diff.
This is because of changes like the following:

![Example diff](https://github.com/google/comprehensive-rust/assets/35542741/9ae927ab-ef67-45a1-807f-5845bd824412)

I'm pretty sure this is because of this (default) setting:
<img width="546" alt="image" src="https://github.com/google/comprehensive-rust/assets/35542741/d6c1b6a2-6225-4835-8d65-16eb2bece01c">

Unfortunately I couldn't find anything in your guidelines that discloses this information.
Any help or clarification on this would be appreciated!

**Comment by mgeisler** [comment]
Please see #800 where @CoinEZ-JPN started a discussion about exactly this. I'll close this and let you continue the discussion there.
