### ISSUE TITLE
The AIDL service section can be improved

### ISSUE THREAD

**Issue by 0nlyjazz** [google/comprehensive-rust#829]
Hello, 
I am interested into performing binder IPC using Rust (of course with AIDL as backend). 
The relevant section of the course introduces to only basic service and client creation. While it serves the purpose but one of the crucial aspect has been missed out i.e. the "extension" portion.

As we know, it is strongly discouraged to modify the frozen APIs rather introduce new ones as an "extension" to a AIDL service.
For example, if I want to add extra functionality to an existing "provider" service, I should register my extension.

In C++ it can be easily done using "setExtension" function call. I have currently no idea how to do it in Rust. 
It would be really helpful if it was shown to us how we can achieve the same functionality in Rust binder service.

Thank you.

**Comment by smore-lore** [comment]
Seems like that is missing, but Rust _is_ documented here:
https://source.android.com/docs/core/architecture/aidl/aidl-backends

Anyway, I've added notes about Rust's 'set_extension' function:
https://source.android.com/docs/core/architecture/aidl/aidl-hals#attached-extensions

Of course, that is a small note, but looking at the function itself, you can see more extensive documentation:
https://cs.android.com/android/platform/superproject/+/master:frameworks/native/libs/binder/rust/src/native.rs;l=106;drc=3d5ca6b066f37aa40433cbd3ba35283fd52090ea

**Comment by maurer** [comment]
Thanks @smore-lore
