### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#836]
Thanks @git-user-cpp for starting this in #835. This issue is to track the translation. Please read the instructions linked in #282, in particular, please read the [translation instructions](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md) and the [style guide](https://github.com/google/comprehensive-rust/blob/main/STYLE.md).

The Rust book has been [translated into Ukrainian](https://github.com/rust-lang-ua/rustbook_ukrainian) and it would be good to use its terminology where possible.

If there are many translators, consider using [this sheet](https://docs.google.com/spreadsheets/d/1-EeAaa_pDkBM1j2mOIv5UXngNOwrq4AH8EO_vIakOYU/template/preview) to coordinate the work. This has been helpful for the Chinese and Japanese translations.

**Comment by PetroProtsyk** [comment]
Hi there, I'd be happy to help with translation

**Comment by mgeisler** [comment]
Thanks @PetroProtsyk and @yaremam! The first thing to do would be to skim through #835 so we can get it merged. The first commit is always huge, so don't worry about that — we just need the ~73 translated messages proofread and someone needs to click the "Approve" button (anybody can do this).

If you end up being many translators here, then I suggest using the spreadsheet template linked above to coordinate. But it's really up to you — comments on this issue could also be more than enough. I'll let you discuss this with @git-user-cpp.

**Comment by dyeroshenko** [comment]
Merged the initial PR and we can start working on improvements in the next iterations. FYI - there is an amazing [vocabulary](https://github.com/rust-lang-ua/rustbook_ukrainian/blob/master/DICTIONARY.md) (proudly borrowed from [Rustbook Ukrainian repo](https://github.com/rust-lang-ua/rustbook_ukrainian)) we can reuse & contribute to.

**Comment by yaremam** [comment]
Is anyone actively working on this?  I created the spreadsheet from the template above - https://docs.google.com/spreadsheets/d/10is7_b4dTzHTzzAJB067vG2LGEY-VekJFsaVjV1j6DU/ 
Please request access and pick your files to translate. I am going to start with welcome.md

**Comment by mgeisler** [comment]
Hi @yaremam, welcome! I don't think anybody is working actively on this.

Consider using https://github.com/mgeisler/cloud-translate to seed the translation with a machine translation. The results are sometimes hilarious, but sometimes helpful :smile:

**Comment by mgeisler** [comment]
You should start by refreshing the PO file by extracting new strings with a 0.2 version of mdbook-i18n-helpers and then run `msgmerge`. That will give you a gigantic PR which @henrif75 or myself can auto-approve. After that, you can submit smaller PRs for a while.

**Comment by yaremam** [comment]
Can't change the reviewer on the PR to @henrif75 or @mgeisler . Looks like previous version was already using 0.2.2 version of mdbook-i18n-helpers though

**Comment by yaremam** [comment]
I think it is best to split the work by ID range, not by source file. I will update the sheet accordingly, let's divide in ranges of 200 strings, so we can merge the work frequently to the master. @PetroProtsyk @dyeroshenko

**Comment by PetroProtsyk** [comment]
Sounds good, I have reserved message ids 401-600

**Comment by yaremam** [comment]
Should we try running cloud-translate? Last time I was using google translator to translate US Army manuals to Ukrainian it produced very good results. @PetroProtsyk @dyeroshenko

**Comment by thefirans** [comment]
Hello guys! I would like to help you with this issue. If there any translations that I can do? @yaremam

**Comment by yaremam** [comment]
@thefirans  -  pick an available range from https://docs.google.com/spreadsheets/d/10is7_b4dTzHTzzAJB067vG2LGEY-VekJFsaVjV1j6DU/ .  You can also try cloud-translate as mentioned here - https://github.com/google/comprehensive-rust/issues/836#issuecomment-1715231643

**Comment by thefirans** [comment]
@yaremam - I translated `uk.po` file using cloud-translate + made some edits to the translation. But I can't run the book with the updated translation, the book still runs on the default localization (even other localizations are not applied). Can you try to run my `uk.po` file on your computer?

**Comment by yaremam** [comment]
I am OOO, without a computer, will be back on October 23rd…


пт, 13 жовт. 2023 р. о 16:27 Alex Leoshko ***@***.***> пише:

**Comment by PetroProtsyk** [comment]
Hi @thefirans, I can give it a try. How can I get your translated `uk.po`?

**Comment by thefirans** [comment]
Hi @PetroProtsyk - it would be great! Here's my translated `uk.po` file from my fork - [link](https://github.com/thefirans/comprehensive-rust/blob/main/po/uk.po)

**Comment by PetroProtsyk** [comment]
Hi @thefirans, I have tried your `uk.po` file. I have used the following commands:

```
MDBOOK_BOOK__LANGUAGE=uk mdbook build -d book/uk
MDBOOK_BOOK__LANGUAGE=uk mdbook serve -d book/uk
```

This will indeed **not** display many new translations. This is because all of them are marked with `fuzzy` flag. See: https://github.com/google/mdbook-i18n-helpers/blob/main/i18n-helpers/USAGE.md#using-translations

If you want to see translated text - you should open your `uk.po` and remove all `#, fuzzy` lines from it. Once you do this, you will see all translations.

**Comment by yaremam** [comment]
I suggest to commit cloud-translate work, and we'll further focus on correcting all fuzzy translations

**Comment by thefirans** [comment]
Would you mind if I create a PR and commit to the main branch for the ```cloud-translate``` work, or is there a specific branch for commits like this? This way, we won't have to translate the ```uk.po``` file from scratch.

**Comment by yaremam** [comment]
Sure, why not, let's commit to the main branch

**Comment by reta** [comment]
> Sure, why not, let's commit to the main branch

@yaremam I would love to help with the translation, would you mind if I work through https://github.com/google/comprehensive-rust/pull/1425 to fix the translation? Thank you.

**Comment by reta** [comment]
@mgeisler we are in a good shape to have Ukrainian translation published (final touches are here https://github.com/google/comprehensive-rust/pull/2176), what is the process to do that? Thank you!

**Comment by henrif75** [comment]
That's great, @reta !
I'll send the PRs to "officially" add the UK translation to the language selector!

**Comment by mgeisler** [comment]
Amazing work, thanks everyone!

**Comment by mgeisler** [comment]
Ukrainian is now the language with the most complete translation: https://google.github.io/comprehensive-rust/synced-translation-report.html. The report shows the result of extracting new strings and merging them into the translation file. There is current 71 untranslated strings.

**Comment by reta** [comment]
> There is current 71 untranslated strings.

I will take care of it shortly, thanks @mgeisler !

**Comment by mgeisler** [comment]
Amazing work!
