### ISSUE TITLE
pt-BR: Coordinating updates and additional translations

### ISSUE THREAD

**Issue by henrif75** [google/comprehensive-rust#893]
I'm creating this issue to coordinate additional work on the pt-BR translation.
Continuation of #317

**Comment by henrif75** [comment]
I'll be working on ch. 6 to 10 for the next week.

**Comment by mgeisler** [comment]
Cc: @rastringer, @hugojacob, and @joaovicmendes, if you haven't seen it.

**Comment by joaovicmendes** [comment]
Awesome idea, @henrif75!
I'll probably work on it mostly Friday, so I think I can work on chap 11 to 17 (day 2 morning, basically).

**Comment by henrif75** [comment]
Thanks @joaovicmendes! 
I'll tackle now the day 2 afternoon, ch. 18 to 21.

**Comment by joaovicmendes** [comment]
Thanks @henrif75! This week I'll try to work on Chapters 22 - 26 (Day 3 Morning)

**Comment by henrif75** [comment]
> Thanks @henrif75! This week I'll try to work on Chapters 22 - 26 (Day 3 Morning)

Sounds good! I'll work on Day 3 afternoon (Ch. 27 - 30)

**Comment by henrif75** [comment]
@joaovicmendes @mgeisler @rastringer @hugojacob 
Hey folks, I'm planning to send a PR only to normalize the format of the pt-br.po file through msgmerge et. al. I anticipate it will be large but mostly changing the lovely line wrapping - as we've been discussing in #800

**Comment by henrif75** [comment]
I'll begin reviewing/updating the Android section.

**Comment by henrif75** [comment]
Great, thanks @rastringer for the PR #1120 
I'll work on removing the fuzzy entries for the next day.

**Comment by henrif75** [comment]
Closing this issue since we're done with the core translation work.
