### ISSUE TITLE
Refresh Korean translation

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#925]
The Korean translation has fallen behind and needs to be refreshed.

This is a continuation of #262.

**Comment by mgeisler** [comment]
With these PRs, the course should be fully translated again. I split the changes into a PR per top-level file, which I hope helps make it easier to review.

Many of the PRs just complete the missing code snippets: #926, #927, #929, #930, #931, #932, #934, #936, #938, #943, #944, #947, #948, #949. This makes them trivial to review (and in hind-sights, I should not have sent them to our translators in the first place).

**Comment by jiyongp** [comment]
Thanks for splitting this up. I and jooyung will review these. Day 1 and 2 for me, the rest for jooyung.

By the way, how are we supposed to do the review? Just leave comments and then translators will fix them? Or are we required to amend the changes by ourselves?

**Comment by mgeisler** [comment]
> By the way, how are we supposed to do the review? Just leave comments and then translators will fix them? Or are we required to amend the changes by ourselves?

Please use the suggestion feature — the Localization team won't see the fixes made here since it's outside of their system. I'll blindly accept any suggestions you have :smile:

**Comment by jiyongp** [comment]
Cool. Ack.

**Comment by mgeisler** [comment]
Great! We should also consider finding more interested people who can help with this — this could be a great starter task since the PRs ought to be mostly ready to merge.

**Comment by jiyongp** [comment]
I've reviewed and amended most of the PRs except #928 (bare metal) and #945 (async), both of which are major additions since the last translation. Reviewing these will take more time than the others.

**Comment by jiyongp** [comment]
Let me take #945. @jooyunghan could you take #928?

**Comment by mgeisler** [comment]
Hi all! I wanted to let you know about #1460. This is an update to mdbook-i18n-helpers which will remove ~6k lines from your PO file. It changes the way code blocks are processed: we now extract strings and comments directly.

You need to run `mdbook-i18n-normalize` on your PO file to preserve the translations found here: https://google.github.io/comprehensive-rust/ko/hello-world/small-example.html (and any other places where you have translated comments).

You can do this before/after refreshing the translation. See #1461 for an example PR which shows the state after normalization.

**Comment by henrif75** [comment]
Closing this issue since we're done with the core translation work on v.2
